import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Header
    appName: 'Derma Assist',
    poweredBy: 'Powered by Deep Learning',
    home: 'Home',
    faq: 'FAQ',
    about: 'About',
    
    // Hero
    heroTitle: 'AI-Powered Skin Disease Detection',
    heroSubtitle: 'Upload an image and let our AI assistant guide you through a quick diagnosis. Answer a few questions for the most accurate results.',
    
    // Tabs
    smartAssistant: 'Smart Assistant',
    imageOnly: 'Image Only',
    symptomsOnly: 'Symptoms Only',
    
    // Chatbot
    welcomeMessage: "👋 Hello! I'm your skin health assistant. Please upload an image of the affected skin area to begin the analysis.",
    uploadImage: 'Upload Image',
    takePhoto: 'Take Photo',
    chooseFile: 'Choose File',
    analyzing: 'Analyzing your image... Please wait.',
    imageReceived: '✅ Image received! I\'ve analyzed your image. Now I need to ask you a few questions about your symptoms to provide the most accurate diagnosis.',
    connectionError: '❌ Connection error. Please make sure the server is running and try again.',
    analysisError: '❌ Sorry, there was an error analyzing the image. Please try again.',
    yes: 'Yes',
    no: 'No',
    
    // Upload Section
    uploadTitle: 'Upload Image',
    clickToUpload: 'Click to upload',
    orDragDrop: 'or drag and drop',
    fileTypes: 'PNG, JPG, JPEG (Max 10MB)',
    analyzeImage: 'Analyze Image',
    analyzingBtn: 'Analyzing...',
    tipsTitle: 'Tips for best results',
    tip1: 'Use clear, well-lit photos',
    tip2: 'Focus on the affected skin area',
    tip3: 'Avoid blurry or distant shots',
    tip4: 'Include only skin images',
    
    // Supported Diseases
    conditionsTitle: 'Conditions We Can Detect',
    learnMore: 'Learn More',
    symptoms: 'Common Symptoms',
    causes: 'Causes',
    prevalence: 'Prevalence',
    severity: 'Severity',
    close: 'Close',
    
    // Disease names
    acne: 'Acne',
    acneDesc: 'Pimples, blackheads, whiteheads',
    chickenpox: 'Chickenpox',
    chickenpoxDesc: 'Itchy blisters, fever, rash',
    healthySkin: 'Healthy Skin',
    healthySkinDesc: 'Normal, healthy appearance',
    psoriasis: 'Psoriasis',
    psoriasisDesc: 'Red patches, silvery scales',
    skinCancer: 'Skin Cancer',
    skinCancerDesc: 'Changing moles, new growths',
    vitiligo: 'Vitiligo',
    vitiligoDesc: 'White patches, depigmentation',
    
    // Camera
    cameraTitle: 'Take a Photo',
    switchCamera: 'Switch Camera',
    capture: 'Capture',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    cameraError: 'Unable to access camera. Please check permissions.',
    
    // Image Validation
    invalidFileType: 'Invalid file type. Please upload JPG, PNG, or WEBP images.',
    fileTooLarge: 'File is too large. Maximum size is 10MB.',
    imageTooSmall: 'Image is too small. Please upload a clearer, larger image.',
    invalidImage: 'Could not load image. Please try a different file.',
    clearImage: 'Clear image',
    clearAndTryAgain: 'Clear and try again',
    
    // Results
    results: 'Results',
    confidence: 'Confidence',
    recommendation: 'Recommendation',
    disclaimer: 'Disclaimer: This is not a medical diagnosis. Please consult a healthcare professional.',
    
    // Footer
    footerText: '© 2026 Derma Assist. For educational purposes only.',
    privacyNote: 'Your images are processed securely and not stored.',
  },
  ta: {
    // Tamil
    appName: 'SkinAI கண்டறிதல்',
    poweredBy: 'டீப் லேர்னிங் மூலம் இயக்கப்படுகிறது',
    home: 'முகப்பு',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    about: 'எங்களைப் பற்றி',
    heroTitle: 'AI-இயக்கப்படும் தோல் நோய் கண்டறிதல்',
    heroSubtitle: 'ஒரு படத்தை பதிவேற்றவும், எங்கள் AI உதவியாளர் விரைவான நோயறிதலுக்கு உங்களை வழிநடத்தும். மிகவும் துல்லியமான முடிவுகளுக்கு சில கேள்விகளுக்கு பதிலளிக்கவும்.',
    smartAssistant: 'ஸ்மார்ட் உதவியாளர்',
    imageOnly: 'படம் மட்டும்',
    symptomsOnly: 'அறிகுறிகள் மட்டும்',
    welcomeMessage: '👋 வணக்கம்! நான் உங்கள் தோல் ஆரோக்கிய உதவியாளர். பாதிக்கப்பட்ட தோல் பகுதியின் படத்தை பதிவேற்றவும்.',
    uploadImage: 'படம் பதிவேற்று',
    takePhoto: 'புகைப்படம் எடு',
    chooseFile: 'கோப்பைத் தேர்ந்தெடுக்கவும்',
    analyzing: 'உங்கள் படத்தை பகுப்பாய்வு செய்கிறது... காத்திருக்கவும்.',
    imageReceived: '✅ படம் பெறப்பட்டது! துல்லியமான நோயறிதலுக்கு சில கேள்விகளுக்கு பதிலளிக்கவும்.',
    connectionError: '❌ இணைப்பு பிழை. சேவையகம் இயங்குகிறதா என்பதை உறுதிசெய்து மீண்டும் முயற்சிக்கவும்.',
    analysisError: '❌ மன்னிக்கவும், படத்தை பகுப்பாய்வு செய்வதில் பிழை. மீண்டும் முயற்சிக்கவும்.',
    yes: 'ஆம்',
    no: 'இல்லை',
    uploadTitle: 'படம் பதிவேற்று',
    clickToUpload: 'பதிவேற்ற கிளிக் செய்யவும்',
    orDragDrop: 'அல்லது இழுத்து விடவும்',
    fileTypes: 'PNG, JPG, JPEG (அதிகபட்சம் 10MB)',
    analyzeImage: 'படத்தை பகுப்பாய்வு செய்',
    analyzingBtn: 'பகுப்பாய்வு செய்கிறது...',
    tipsTitle: 'சிறந்த முடிவுகளுக்கான குறிப்புகள்',
    tip1: 'தெளிவான, நன்கு வெளிச்சமான புகைப்படங்களைப் பயன்படுத்தவும்',
    tip2: 'பாதிக்கப்பட்ட தோல் பகுதியில் கவனம் செலுத்தவும்',
    tip3: 'மங்கலான அல்லது தொலைவிலிருந்து எடுத்த படங்களைத் தவிர்க்கவும்',
    tip4: 'தோல் படங்களை மட்டும் சேர்க்கவும்',
    conditionsTitle: 'நாங்கள் கண்டறியக்கூடிய நிலைகள்',
    learnMore: 'மேலும் அறிய',
    symptoms: 'பொதுவான அறிகுறிகள்',
    causes: 'காரணங்கள்',
    prevalence: 'பரவல்',
    severity: 'தீவிரம்',
    close: 'மூடு',
    acne: 'முகப்பரு',
    acneDesc: 'பருக்கள், கரும்புள்ளிகள், வெண்புள்ளிகள்',
    chickenpox: 'சின்னம்மை',
    chickenpoxDesc: 'அரிப்பு கொப்புளங்கள், காய்ச்சல், தடிப்பு',
    healthySkin: 'ஆரோக்கியமான தோல்',
    healthySkinDesc: 'இயல்பான, ஆரோக்கியமான தோற்றம்',
    psoriasis: 'சொரியாசிஸ்',
    psoriasisDesc: 'சிவப்பு திட்டுகள், வெள்ளி செதில்கள்',
    skinCancer: 'தோல் புற்றுநோய்',
    skinCancerDesc: 'மாறும் மச்சங்கள், புதிய வளர்ச்சிகள்',
    vitiligo: 'வெண்குஷ்டம்',
    vitiligoDesc: 'வெள்ளை திட்டுகள், நிறமிழப்பு',
    cameraTitle: 'புகைப்படம் எடு',
    switchCamera: 'கேமரா மாற்று',
    capture: 'படமெடு',
    retake: 'மீண்டும் எடு',
    usePhoto: 'புகைப்படத்தைப் பயன்படுத்து',
    cameraError: 'கேமராவை அணுக முடியவில்லை. அனுமதிகளை சரிபார்க்கவும்.',
    invalidFileType: 'தவறான கோப்பு வகை. JPG, PNG அல்லது WEBP படங்களை பதிவேற்றவும்.',
    fileTooLarge: 'கோப்பு மிகப் பெரியது. அதிகபட்ச அளவு 10MB.',
    imageTooSmall: 'படம் மிகச் சிறியது. தெளிவான, பெரிய படத்தை பதிவேற்றவும்.',
    invalidImage: 'படத்தை ஏற்ற முடியவில்லை. வேறு கோப்பை முயற்சிக்கவும்.',
    clearImage: 'படத்தை அழி',
    clearAndTryAgain: 'அழித்து மீண்டும் முயற்சிக்கவும்',
    results: 'முடிவுகள்',
    confidence: 'நம்பகத்தன்மை',
    recommendation: 'பரிந்துரை',
    disclaimer: 'மறுப்பு: இது மருத்துவ நோயறிதல் அல்ல. சுகாதார நிபுணரை அணுகவும்.',
    footerText: '© 2026 SkinAI கண்டறிதல். கல்வி நோக்கங்களுக்கு மட்டும்.',
    privacyNote: 'உங்கள் படங்கள் பாதுகாப்பாக செயலாக்கப்படுகின்றன, சேமிக்கப்படுவதில்லை.',
  },
  hi: {
    // Hindi
    appName: 'SkinAI डिटेक्टर',
    poweredBy: 'डीप लर्निंग द्वारा संचालित',
    home: 'होम',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    about: 'हमारे बारे में',
    heroTitle: 'AI-संचालित त्वचा रोग पहचान',
    heroSubtitle: 'एक छवि अपलोड करें और हमारे AI सहायक को त्वरित निदान में आपका मार्गदर्शन करने दें। सबसे सटीक परिणामों के लिए कुछ प्रश्नों के उत्तर दें।',
    smartAssistant: 'स्मार्ट सहायक',
    imageOnly: 'केवल छवि',
    symptomsOnly: 'केवल लक्षण',
    welcomeMessage: '👋 नमस्ते! मैं आपका त्वचा स्वास्थ्य सहायक हूं। विश्लेषण शुरू करने के लिए कृपया प्रभावित त्वचा क्षेत्र की एक छवि अपलोड करें।',
    uploadImage: 'छवि अपलोड करें',
    takePhoto: 'फोटो लें',
    chooseFile: 'फ़ाइल चुनें',
    analyzing: 'आपकी छवि का विश्लेषण किया जा रहा है... कृपया प्रतीक्षा करें।',
    imageReceived: '✅ छवि प्राप्त हुई! मैंने आपकी छवि का विश्लेषण कर लिया है। अब मुझे सबसे सटीक निदान प्रदान करने के लिए आपके लक्षणों के बारे में कुछ प्रश्न पूछने होंगे।',
    connectionError: '❌ कनेक्शन त्रुटि। कृपया सुनिश्चित करें कि सर्वर चल रहा है और पुनः प्रयास करें।',
    analysisError: '❌ क्षमा करें, छवि का विश्लेषण करने में त्रुटि हुई। कृपया पुनः प्रयास करें।',
    yes: 'हाँ',
    no: 'नहीं',
    uploadTitle: 'छवि अपलोड करें',
    clickToUpload: 'अपलोड करने के लिए क्लिक करें',
    orDragDrop: 'या खींचें और छोड़ें',
    fileTypes: 'PNG, JPG, JPEG (अधिकतम 10MB)',
    analyzeImage: 'छवि का विश्लेषण करें',
    analyzingBtn: 'विश्लेषण हो रहा है...',
    tipsTitle: 'सर्वोत्तम परिणामों के लिए सुझाव',
    tip1: 'स्पष्ट, अच्छी रोशनी वाली तस्वीरें उपयोग करें',
    tip2: 'प्रभावित त्वचा क्षेत्र पर फोकस करें',
    tip3: 'धुंधली या दूर की तस्वीरों से बचें',
    tip4: 'केवल त्वचा की छवियां शामिल करें',
    conditionsTitle: 'हम जिन स्थितियों का पता लगा सकते हैं',
    learnMore: 'और जानें',
    symptoms: 'सामान्य लक्षण',
    causes: 'कारण',
    prevalence: 'व्यापकता',
    severity: 'गंभीरता',
    close: 'बंद करें',
    acne: 'मुँहासे',
    acneDesc: 'फुंसी, ब्लैकहेड्स, व्हाइटहेड्स',
    chickenpox: 'चिकनपॉक्स',
    chickenpoxDesc: 'खुजली वाले छाले, बुखार, दाने',
    healthySkin: 'स्वस्थ त्वचा',
    healthySkinDesc: 'सामान्य, स्वस्थ दिखावट',
    psoriasis: 'सोरायसिस',
    psoriasisDesc: 'लाल धब्बे, चांदी जैसी पपड़ी',
    skinCancer: 'त्वचा कैंसर',
    skinCancerDesc: 'बदलते तिल, नई वृद्धि',
    vitiligo: 'विटिलिगो',
    vitiligoDesc: 'सफेद धब्बे, रंग का नुकसान',
    cameraTitle: 'फोटो लें',
    switchCamera: 'कैमरा बदलें',
    capture: 'कैप्चर',
    retake: 'फिर से लें',
    usePhoto: 'फोटो उपयोग करें',
    cameraError: 'कैमरा एक्सेस नहीं हो पा रहा। कृपया अनुमतियां जांचें।',
    invalidFileType: 'अमान्य फ़ाइल प्रकार। कृपया JPG, PNG या WEBP छवियां अपलोड करें।',
    fileTooLarge: 'फ़ाइल बहुत बड़ी है। अधिकतम आकार 10MB है।',
    imageTooSmall: 'छवि बहुत छोटी है। कृपया एक स्पष्ट, बड़ी छवि अपलोड करें।',
    invalidImage: 'छवि लोड नहीं हो सकी। कृपया दूसरी फ़ाइल आज़माएं।',
    clearImage: 'छवि साफ़ करें',
    clearAndTryAgain: 'साफ़ करें और फिर से प्रयास करें',
    results: 'परिणाम',
    confidence: 'विश्वास',
    recommendation: 'सिफारिश',
    disclaimer: 'अस्वीकरण: यह चिकित्सा निदान नहीं है। कृपया स्वास्थ्य पेशेवर से परामर्श करें।',
    footerText: '© 2026 SkinAI डिटेक्टर। केवल शैक्षिक उद्देश्यों के लिए।',
    privacyNote: 'आपकी छवियां सुरक्षित रूप से संसाधित की जाती हैं और संग्रहीत नहीं की जातीं।',
  },
  ml: {
    // Malayalam
    appName: 'SkinAI ഡിറ്റക്ടർ',
    poweredBy: 'ഡീപ് ലേണിംഗ് ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്നു',
    home: 'ഹോം',
    faq: 'പതിവ് ചോദ്യങ്ങൾ',
    about: 'ഞങ്ങളെക്കുറിച്ച്',
    heroTitle: 'AI-പവർഡ് ത്വക്ക് രോഗ കണ്ടെത്തൽ',
    heroSubtitle: 'ഒരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക, ഞങ്ങളുടെ AI അസിസ്റ്റന്റ് വേഗത്തിലുള്ള രോഗനിർണയത്തിലൂടെ നിങ്ങളെ നയിക്കും.',
    smartAssistant: 'സ്മാർട്ട് അസിസ്റ്റന്റ്',
    imageOnly: 'ചിത്രം മാത്രം',
    symptomsOnly: 'ലക്ഷണങ്ങൾ മാത്രം',
    welcomeMessage: '👋 ഹലോ! ഞാൻ നിങ്ങളുടെ ത്വക്ക് ആരോഗ്യ അസിസ്റ്റന്റാണ്. വിശകലനം ആരംഭിക്കാൻ ബാധിത ത്വക്ക് പ്രദേശത്തിന്റെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.',
    uploadImage: 'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    takePhoto: 'ഫോട്ടോ എടുക്കുക',
    chooseFile: 'ഫയൽ തിരഞ്ഞെടുക്കുക',
    analyzing: 'നിങ്ങളുടെ ചിത്രം വിശകലനം ചെയ്യുന്നു... കാത്തിരിക്കുക.',
    imageReceived: '✅ ചിത്രം ലഭിച്ചു! കൃത്യമായ രോഗനിർണയത്തിനായി കുറച്ച് ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകുക.',
    connectionError: '❌ കണക്ഷൻ പിശക്. സെർവർ പ്രവർത്തിക്കുന്നുണ്ടെന്ന് ഉറപ്പാക്കി വീണ്ടും ശ്രമിക്കുക.',
    analysisError: '❌ ക്ഷമിക്കണം, ചിത്രം വിശകലനം ചെയ്യുന്നതിൽ പിശക്. വീണ്ടും ശ്രമിക്കുക.',
    yes: 'അതെ',
    no: 'ഇല്ല',
    uploadTitle: 'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    clickToUpload: 'അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക',
    orDragDrop: 'അല്ലെങ്കിൽ വലിച്ചിടുക',
    fileTypes: 'PNG, JPG, JPEG (പരമാവധി 10MB)',
    analyzeImage: 'ചിത്രം വിശകലനം ചെയ്യുക',
    analyzingBtn: 'വിശകലനം ചെയ്യുന്നു...',
    tipsTitle: 'മികച്ച ഫലങ്ങൾക്കുള്ള നുറുങ്ങുകൾ',
    tip1: 'വ്യക്തമായ, നന്നായി പ്രകാശിതമായ ഫോട്ടോകൾ ഉപയോഗിക്കുക',
    tip2: 'ബാധിത ത്വക്ക് പ്രദേശത്ത് ശ്രദ്ധ കേന്ദ്രീകരിക്കുക',
    tip3: 'മങ്ങിയതോ ദൂരെ നിന്നുള്ളതോ ആയ ഷോട്ടുകൾ ഒഴിവാക്കുക',
    tip4: 'ത്വക്ക് ചിത്രങ്ങൾ മാത്രം ഉൾപ്പെടുത്തുക',
    conditionsTitle: 'ഞങ്ങൾക്ക് കണ്ടെത്താൻ കഴിയുന്ന അവസ്ഥകൾ',
    learnMore: 'കൂടുതൽ അറിയുക',
    symptoms: 'സാധാരണ ലക്ഷണങ്ങൾ',
    causes: 'കാരണങ്ങൾ',
    prevalence: 'വ്യാപനം',
    severity: 'തീവ്രത',
    close: 'അടയ്ക്കുക',
    acne: 'മുഖക്കുരു',
    acneDesc: 'പരുക്കൾ, കറുത്ത പുള്ളികൾ, വെളുത്ത പുള്ളികൾ',
    chickenpox: 'ചിക്കൻപോക്സ്',
    chickenpoxDesc: 'ചൊറിച്ചിലുള്ള കുമിളകൾ, പനി, ചുണങ്ങ്',
    healthySkin: 'ആരോഗ്യകരമായ ത്വക്ക്',
    healthySkinDesc: 'സാധാരണ, ആരോഗ്യകരമായ രൂപം',
    psoriasis: 'സോറിയാസിസ്',
    psoriasisDesc: 'ചുവന്ന പാടുകൾ, വെള്ളി ചെതുമ്പലുകൾ',
    skinCancer: 'ത്വക്ക് കാൻസർ',
    skinCancerDesc: 'മാറുന്ന മറുകുകൾ, പുതിയ വളർച്ചകൾ',
    vitiligo: 'വിറ്റിലിഗോ',
    vitiligoDesc: 'വെളുത്ത പാടുകൾ, നിറം നഷ്ടപ്പെടൽ',
    cameraTitle: 'ഫോട്ടോ എടുക്കുക',
    switchCamera: 'ക്യാമറ മാറ്റുക',
    capture: 'പിടിച്ചെടുക്കുക',
    retake: 'വീണ്ടും എടുക്കുക',
    usePhoto: 'ഫോട്ടോ ഉപയോഗിക്കുക',
    cameraError: 'ക്യാമറ ആക്സസ് ചെയ്യാൻ കഴിയുന്നില്ല. അനുമതികൾ പരിശോധിക്കുക.',
    invalidFileType: 'അസാധുവായ ഫയൽ തരം. JPG, PNG അല്ലെങ്കിൽ WEBP ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുക.',
    fileTooLarge: 'ഫയൽ വളരെ വലുതാണ്. പരമാവധി വലുപ്പം 10MB.',
    imageTooSmall: 'ചിത്രം വളരെ ചെറുതാണ്. കൂടുതൽ വ്യക്തമായ, വലിയ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.',
    invalidImage: 'ചിത്രം ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല. മറ്റൊരു ഫയൽ ശ്രമിക്കുക.',
    clearImage: 'ചിത്രം മായ്ക്കുക',
    clearAndTryAgain: 'മായ്ച്ച് വീണ്ടും ശ്രമിക്കുക',
    results: 'ഫലങ്ങൾ',
    confidence: 'വിശ്വാസ്യത',
    recommendation: 'ശുപാർശ',
    disclaimer: 'നിരാകരണം: ഇത് മെഡിക്കൽ രോഗനിർണയമല്ല. ആരോഗ്യ വിദഗ്ധനെ സമീപിക്കുക.',
    footerText: '© 2026 SkinAI ഡിറ്റക്ടർ. വിദ്യാഭ്യാസ ആവശ്യങ്ങൾക്ക് മാത്രം.',
    privacyNote: 'നിങ്ങളുടെ ചിത്രങ്ങൾ സുരക്ഷിതമായി പ്രോസസ്സ് ചെയ്യുന്നു, സംഭരിക്കുന്നില്ല.',
  },
  te: {
    // Telugu
    appName: 'SkinAI డిటెక్టర్',
    poweredBy: 'డీప్ లెర్నింగ్ ద్వారా ఆధారితం',
    home: 'హోమ్',
    faq: 'తరచుగా అడిగే ప్రశ్నలు',
    about: 'మా గురించి',
    heroTitle: 'AI-ఆధారిత చర్మ వ్యాధి గుర్తింపు',
    heroSubtitle: 'చిత్రాన్ని అప్‌లోడ్ చేయండి, మా AI అసిస్టెంట్ త్వరిత రోగ నిర్ధారణలో మీకు మార్గనిర్దేశం చేస్తుంది.',
    smartAssistant: 'స్మార్ట్ అసిస్టెంట్',
    imageOnly: 'చిత్రం మాత్రమే',
    symptomsOnly: 'లక్షణాలు మాత్రమే',
    welcomeMessage: '👋 హలో! నేను మీ చర్మ ఆరోగ్య అసిస్టెంట్‌ని. విశ్లేషణ ప్రారంభించడానికి ప్రభావిత చర్మ ప్రాంతం చిత్రాన్ని అప్‌లోడ్ చేయండి.',
    uploadImage: 'చిత్రం అప్‌లోడ్ చేయండి',
    takePhoto: 'ఫోటో తీయండి',
    chooseFile: 'ఫైల్ ఎంచుకోండి',
    analyzing: 'మీ చిత్రాన్ని విశ్లేషిస్తోంది... దయచేసి వేచి ఉండండి.',
    imageReceived: '✅ చిత్రం అందింది! ఖచ్చితమైన రోగ నిర్ధారణ కోసం కొన్ని ప్రశ్నలకు సమాధానం ఇవ్వండి.',
    connectionError: '❌ కనెక్షన్ ఎర్రర్. సర్వర్ రన్ అవుతోందని నిర్ధారించుకుని మళ్ళీ ప్రయత్నించండి.',
    analysisError: '❌ క్షమించండి, చిత్రాన్ని విశ్లేషించడంలో లోపం. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    yes: 'అవును',
    no: 'కాదు',
    uploadTitle: 'చిత్రం అప్‌లోడ్ చేయండి',
    clickToUpload: 'అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    orDragDrop: 'లేదా డ్రాగ్ అండ్ డ్రాప్ చేయండి',
    fileTypes: 'PNG, JPG, JPEG (గరిష్టం 10MB)',
    analyzeImage: 'చిత్రాన్ని విశ్లేషించండి',
    analyzingBtn: 'విశ్లేషిస్తోంది...',
    tipsTitle: 'ఉత్తమ ఫలితాల కోసం చిట్కాలు',
    tip1: 'స్పష్టమైన, బాగా వెలుతురు ఉన్న ఫోటోలు ఉపయోగించండి',
    tip2: 'ప్రభావిత చర్మ ప్రాంతంపై దృష్టి పెట్టండి',
    tip3: 'అస్పష్టమైన లేదా దూరం నుండి తీసిన షాట్లను నివారించండి',
    tip4: 'చర్మ చిత్రాలను మాత్రమే చేర్చండి',
    conditionsTitle: 'మేము గుర్తించగల పరిస్థితులు',
    learnMore: 'మరింత తెలుసుకోండి',
    symptoms: 'సాధారణ లక్షణాలు',
    causes: 'కారణాలు',
    prevalence: 'వ్యాప్తి',
    severity: 'తీవ్రత',
    close: 'మూసివేయండి',
    acne: 'మొటిమలు',
    acneDesc: 'పింపుల్స్, బ్లాక్‌హెడ్స్, వైట్‌హెడ్స్',
    chickenpox: 'చికెన్‌పాక్స్',
    chickenpoxDesc: 'దురద బొబ్బలు, జ్వరం, దద్దుర్లు',
    healthySkin: 'ఆరోగ్యకరమైన చర్మం',
    healthySkinDesc: 'సాధారణ, ఆరోగ్యకరమైన రూపం',
    psoriasis: 'సోరియాసిస్',
    psoriasisDesc: 'ఎర్రటి మచ్చలు, వెండి పొలుసులు',
    skinCancer: 'చర్మ క్యాన్సర్',
    skinCancerDesc: 'మారుతున్న మచ్చలు, కొత్త పెరుగుదలలు',
    vitiligo: 'విటిలిగో',
    vitiligoDesc: 'తెల్ల మచ్చలు, రంగు కోల్పోవడం',
    cameraTitle: 'ఫోటో తీయండి',
    switchCamera: 'కెమెరా మార్చండి',
    capture: 'క్యాప్చర్',
    retake: 'మళ్ళీ తీయండి',
    usePhoto: 'ఫోటో ఉపయోగించండి',
    cameraError: 'కెమెరా యాక్సెస్ చేయడం సాధ్యం కాలేదు. అనుమతులు తనిఖీ చేయండి.',
    invalidFileType: 'చెల్లని ఫైల్ రకం. JPG, PNG లేదా WEBP చిత్రాలను అప్‌లోడ్ చేయండి.',
    fileTooLarge: 'ఫైల్ చాలా పెద్దది. గరిష్ట పరిమాణం 10MB.',
    imageTooSmall: 'చిత్రం చాలా చిన్నది. స్పష్టమైన, పెద్ద చిత్రాన్ని అప్‌లోడ్ చేయండి.',
    invalidImage: 'చిత్రాన్ని లోడ్ చేయడం సాధ్యం కాలేదు. మరొక ఫైల్ ప్రయత్నించండి.',
    clearImage: 'చిత్రం క్లియర్ చేయండి',
    clearAndTryAgain: 'క్లియర్ చేసి మళ్ళీ ప్రయత్నించండి',
    results: 'ఫలితాలు',
    confidence: 'నమ్మకం',
    recommendation: 'సిఫార్సు',
    disclaimer: 'నిరాకరణ: ఇది వైద్య రోగ నిర్ధారణ కాదు. ఆరోగ్య నిపుణుడిని సంప్రదించండి.',
    footerText: '© 2026 SkinAI డిటెక్టర్. విద్యా ప్రయోజనాల కోసం మాత్రమే.',
    privacyNote: 'మీ చిత్రాలు సురక్షితంగా ప్రాసెస్ చేయబడతాయి, నిల్వ చేయబడవు.',
  },
  kn: {
    // Kannada
    appName: 'SkinAI ಡಿಟೆಕ್ಟರ್',
    poweredBy: 'ಡೀಪ್ ಲರ್ನಿಂಗ್ ಮೂಲಕ ಚಾಲಿತ',
    home: 'ಮುಖಪುಟ',
    faq: 'ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    heroTitle: 'AI-ಚಾಲಿತ ಚರ್ಮ ರೋಗ ಪತ್ತೆ',
    heroSubtitle: 'ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ, ನಮ್ಮ AI ಸಹಾಯಕ ತ್ವರಿತ ರೋಗನిರ್ಣಯದಲ್ಲಿ ನಿಮಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ.',
    smartAssistant: 'ಸ್ಮಾರ್ಟ್ ಸಹಾಯಕ',
    imageOnly: 'ಚಿತ್ರ ಮಾತ್ರ',
    symptomsOnly: 'ರೋಗಲಕ್ಷಣಗಳು ಮಾತ್ರ',
    welcomeMessage: '👋 ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಚರ್ಮ ಆರೋಗ್ಯ ಸಹಾಯಕ. ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಲು ಪ್ರಭಾವಿತ ಚರ್ಮ ಪ್ರದೇಶದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    uploadImage: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    chooseFile: 'ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
    analyzing: 'ನಿಮ್ಮ ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ... ದಯವಿಟ್ಟು ಕಾಯಿರಿ.',
    imageReceived: '✅ ಚಿತ್ರ ಸ್ವೀಕರಿಸಲಾಗಿದೆ! ನಿಖರವಾದ ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಕೆಲವು ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.',
    connectionError: '❌ ಸಂಪರ್ಕ ದೋಷ. ಸರ್ವರ್ ಚಾಲನೆಯಲ್ಲಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಂಡು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    analysisError: '❌ ಕ್ಷಮಿಸಿ, ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸುವಲ್ಲಿ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    uploadTitle: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    clickToUpload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    orDragDrop: 'ಅಥವಾ ಎಳೆದು ಬಿಡಿ',
    fileTypes: 'PNG, JPG, JPEG (ಗರಿಷ್ಠ 10MB)',
    analyzeImage: 'ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    analyzingBtn: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    tipsTitle: 'ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗೆ ಸಲಹೆಗಳು',
    tip1: 'ಸ್ಪಷ್ಟವಾದ, ಚೆನ್ನಾಗಿ ಬೆಳಗಿದ ಫೋಟೋಗಳನ್ನು ಬಳಸಿ',
    tip2: 'ಪ್ರಭಾವಿತ ಚರ್ಮ ಪ್ರದೇಶದ ಮೇಲೆ ಗಮನ ಕೇಂದ್ರೀಕರಿಸಿ',
    tip3: 'ಮಸುಕಾದ ಅಥವಾ ದೂರದ ಶಾಟ್‌ಗಳನ್ನು ತಪ್ಪಿಸಿ',
    tip4: 'ಚರ್ಮದ ಚಿತ್ರಗಳನ್ನು ಮಾತ್ರ ಸೇರಿಸಿ',
    conditionsTitle: 'ನಾವು ಪತ್ತೆಹಚ್ಚಬಹುದಾದ ಸ್ಥಿತಿಗಳು',
    learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    symptoms: 'ಸಾಮಾನ್ಯ ರೋಗಲಕ್ಷಣಗಳು',
    causes: 'ಕಾರಣಗಳು',
    prevalence: 'ಹರಡುವಿಕೆ',
    severity: 'ತೀವ್ರತೆ',
    close: 'ಮುಚ್ಚಿ',
    acne: 'ಮೊಡವೆ',
    acneDesc: 'ಗುಳ್ಳೆಗಳು, ಕಪ್ಪು ಚುಕ್ಕೆಗಳು, ಬಿಳಿ ಚುಕ್ಕೆಗಳು',
    chickenpox: 'ಚಿಕನ್‌ಪಾಕ್ಸ್',
    chickenpoxDesc: 'ತುರಿಕೆ ಗುಳ್ಳೆಗಳು, ಜ್ವರ, ದದ್ದು',
    healthySkin: 'ಆರೋಗ್ಯಕರ ಚರ್ಮ',
    healthySkinDesc: 'ಸಾಮಾನ್ಯ, ಆರೋಗ್ಯಕರ ನೋಟ',
    psoriasis: 'ಸೋರಿಯಾಸಿಸ್',
    psoriasisDesc: 'ಕೆಂಪು ಮಚ್ಚೆಗಳು, ಬೆಳ್ಳಿ ಹುರುಪೆಗಳು',
    skinCancer: 'ಚರ್ಮದ ಕ್ಯಾನ್ಸರ್',
    skinCancerDesc: 'ಬದಲಾಗುತ್ತಿರುವ ಮಚ್ಚೆಗಳು, ಹೊಸ ಬೆಳವಣಿಗೆಗಳು',
    vitiligo: 'ವಿಟಿಲಿಗೋ',
    vitiligoDesc: 'ಬಿಳಿ ಮಚ್ಚೆಗಳು, ಬಣ್ಣ ಕಳೆದುಕೊಳ್ಳುವಿಕೆ',
    cameraTitle: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    switchCamera: 'ಕ್ಯಾಮೆರಾ ಬದಲಾಯಿಸಿ',
    capture: 'ಕ್ಯಾಪ್ಚರ್',
    retake: 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    usePhoto: 'ಫೋಟೋ ಬಳಸಿ',
    cameraError: 'ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ಅನುಮತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    invalidFileType: 'ಅಮಾನ್ಯ ಫೈಲ್ ಪ್ರಕಾರ. JPG, PNG ಅಥವಾ WEBP ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    fileTooLarge: 'ಫೈಲ್ ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ. ಗರಿಷ್ಠ ಗಾತ್ರ 10MB.',
    imageTooSmall: 'ಚಿತ್ರ ತುಂಬಾ ಚಿಕ್ಕದಾಗಿದೆ. ಸ್ಪಷ್ಟವಾದ, ದೊಡ್ಡ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    invalidImage: 'ಚಿತ್ರವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಬೇರೆ ಫೈಲ್ ಪ್ರಯತ್ನಿಸಿ.',
    clearImage: 'ಚಿತ್ರ ತೆರವುಗೊಳಿಸಿ',
    clearAndTryAgain: 'ತೆರವುಗೊಳಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    results: 'ಫಲಿತಾಂಶಗಳು',
    confidence: 'ವಿಶ್ವಾಸ',
    recommendation: 'ಶಿಫಾರಸು',
    disclaimer: 'ಹಕ್ಕುತ್ಯಾಗ: ಇದು ವೈದ್ಯಕೀಯ ರೋಗನಿರ್ಣಯವಲ್ಲ. ಆರೋಗ್ಯ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    footerText: '© 2026 SkinAI ಡಿಟೆಕ್ಟರ್. ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶಗಳಿಗೆ ಮಾತ್ರ.',
    privacyNote: 'ನಿಮ್ಮ ಚಿತ್ರಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಸ್ಕರಿಸಲಾಗುತ್ತದೆ, ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('preferredLanguage');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;