import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Header
    appName: 'Derma Assist',
    poweredBy: 'Powered by Deep Learning',
    home: 'Home',
    faq: 'FAQ',
    about: 'About',
    
    // Hero
    heroTitle: 'AI-Powered Skin Disease Detection',
    heroSubtitle: 'Upload an image and let our AI assistant guide you through a quick diagnosis. Answer a few questions for the most accurate results.',
    
    // Tabs
    smartAssistant: 'Smart Assistant',
    imageOnly: 'Image Only',
    symptomsOnly: 'Symptoms Only',
    
    // Chatbot
    welcomeMessage: "👋 Hello! I'm your skin health assistant. Please upload an image of the affected skin area to begin the analysis.",
    uploadImage: 'Upload Image',
    takePhoto: 'Take Photo',
    chooseFile: 'Choose File',
    analyzing: 'Analyzing your image... Please wait.',
    imageReceived: '✅ Image received! I\'ve analyzed your image. Now I need to ask you a few questions about your symptoms to provide the most accurate diagnosis.',
    connectionError: '❌ Connection error. Please make sure the server is running and try again.',
    analysisError: '❌ Sorry, there was an error analyzing the image. Please try again.',
    yes: 'Yes',
    no: 'No',
    
    // Upload Section
    uploadTitle: 'Upload Image',
    clickToUpload: 'Click to upload',
    orDragDrop: 'or drag and drop',
    fileTypes: 'PNG, JPG, JPEG (Max 10MB)',
    analyzeImage: 'Analyze Image',
    analyzingBtn: 'Analyzing...',
    tipsTitle: 'Tips for best results',
    tip1: 'Use clear, well-lit photos',
    tip2: 'Focus on the affected skin area',
    tip3: 'Avoid blurry or distant shots',
    tip4: 'Include only skin images',
    
    // Supported Diseases
    conditionsTitle: 'Conditions We Can Detect',
    learnMore: 'Learn More',
    symptoms: 'Common Symptoms',
    causes: 'Causes',
    prevalence: 'Prevalence',
    severity: 'Severity',
    close: 'Close',
    
    // Disease names
    acne: 'Acne',
    acneDesc: 'Pimples, blackheads, whiteheads',
    chickenpox: 'Chickenpox',
    chickenpoxDesc: 'Itchy blisters, fever, rash',
    healthySkin: 'Healthy Skin',
    healthySkinDesc: 'Normal, healthy appearance',
    psoriasis: 'Psoriasis',
    psoriasisDesc: 'Red patches, silvery scales',
    skinCancer: 'Skin Cancer',
    skinCancerDesc: 'Changing moles, new growths',
    vitiligo: 'Vitiligo',
    vitiligoDesc: 'White patches, depigmentation',
    
    // Camera
    cameraTitle: 'Take a Photo',
    switchCamera: 'Switch Camera',
    capture: 'Capture',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    cameraError: 'Unable to access camera. Please check permissions.',
    
    // Image Validation
    invalidFileType: 'Invalid file type. Please upload JPG, PNG, or WEBP images.',
    fileTooLarge: 'File is too large. Maximum size is 10MB.',
    imageTooSmall: 'Image is too small. Please upload a clearer, larger image.',
    invalidImage: 'Could not load image. Please try a different file.',
    clearImage: 'Clear image',
    clearAndTryAgain: 'Clear and try again',
    
    // Results
    results: 'Results',
    confidence: 'Confidence',
    recommendation: 'Recommendation',
    disclaimer: 'Disclaimer: This is not a medical diagnosis. Please consult a healthcare professional.',
    
    // Footer
    footerText: '© 2026 Derma Assist. For educational purposes only.',
    privacyNote: 'Your images are processed securely and not stored.',
    selectLanguage: 'Select language',
    heroBadge: 'AI-Powered Detection',
    heroDetail: 'Our advanced system uses YOLO detection, EfficientNetB3 classification, and symptom Q&A to provide a fast preliminary analysis.',
    pleaseUploadImageFirst: 'Please upload or capture an image first.',
    imageAnalysisFailed: 'Image analysis failed.',
    uploadOrCapture: 'Upload or Capture',
    uploadOrCaptureSubtitle: 'Choose an image to analyze',
    dropYourSkinImageHere: 'Drop your skin image here',
    useOneOfButtonsBelow: 'or use one of the buttons below',
    startingCamera: 'Starting camera...',
    initializingCamera: 'Initializing camera...',
    cancel: 'Cancel',
    removeImage: 'Remove image',
    imageReadyForAnalysis: 'Image Ready for Analysis',
    imageRejected: 'INVALID IMAGE',
    pleaseUploadValidImage: 'Please upload a valid image',
    validationFailedPrefix: 'Validation Failed:',
    imageDoesNotMeetRequirements: 'Image does not meet requirements',
    failedToValidateImage: 'Failed to validate image',
    pleaseSelectImageFile: 'Please select an image file.',
    cameraFailedPrefix: 'Camera Failed',
    cameraNotSupported: 'Camera not supported in this browser',
    cameraInitializationFailed: 'Camera initialization failed',
    videoElementNotFound: 'Video element not found. Please refresh and try again.',
    cameraPermissionDenied: 'Camera permission denied. Please allow camera access in browser settings.',
    noCameraDeviceFound: 'No camera device found on this device.',
    cameraAlreadyInUse: 'Camera is already in use. Close other applications using the camera.',
    cameraNotConfigured: 'Camera not available or not properly configured.',
    cameraNotSupportedBrowser: 'Your browser does not support camera access. Try Chrome, Firefox, or Edge.',
    cameraStreamInitializationFailedHelp: 'Camera stream initialization failed. Please refresh the page and try again.',
    unknownCameraError: 'Unknown error occurred.',
    cameraReferenceError: 'Camera reference error. Please refresh and try again.',
    cameraStreamNotReady: 'Camera stream not ready. Please wait and try again.',
    failedToCaptureImage: 'Failed to capture image. Please try again.',
    validatingImageQuality: 'Validating image quality...',
    imageAppearsBlurry: 'Image appears blurry (score: {score}%). Please capture a clearer image.',
    noSkinDetected: 'No skin detected in image (only {percent}% skin tone found). Please provide an image showing skin clearly.',
    imageAppearsShaky: 'Image appears shaky or has motion blur. Please try again with a steadier capture.',
    imageResolutionLow: 'Image resolution is low ({width}x{height}). For better results, please use a higher resolution image.',
    failedToReadImageFile: 'Failed to read image file',
    symptomAssessment: 'Symptom Assessment',
    answerQuestionsToRefineDiagnosis: 'Answer a few quick questions to refine your diagnosis',
    step3Of5: 'STEP 3 of 5',
    helpRefineDiagnosis: 'Help us refine the diagnosis by answering symptom-related questions',
    loadingQuestions: 'Loading Questions...',
    startAssessment: 'Start Assessment',
    tipAnswerQuestions: 'Tip: Answer each question based on your symptoms or observations',
    computingFinalDiagnosis: 'Computing Final Diagnosis...',
    getFinalDiagnosis: 'Get Final Diagnosis',
    failedToLoadQuestions: 'Failed to load questions.',
    failedToComputeFinalDecision: 'Failed to compute final decision',
    finalDiagnosis: 'Final Diagnosis',
    basedOnImageAnalysisAndSymptoms: 'Based on image analysis and symptom assessment',
    step4Of5: 'STEP 4 of 5',
    confidenceScore: 'Confidence Score',
    methodologyAiSymptoms: 'Methodology',
    methodologyAiSymptomsValue: 'AI + Symptoms',
    analysisVisualization: 'Analysis Visualization',
    originalImage: 'Original Image',
    yoloDetectionRedBoxes: 'YOLO Detection (Red Boxes)',
    lesionSegmentation: 'Lesion Segmentation',
    loadingImage: 'Loading image...',
    symptomQuestionsAnalyzed: 'Symptom Questions Analyzed',
    chatQuestionWhitePatches: 'Do you see sharply white patches?',
    chatQuestionPatchesIncreasing: 'Are the patches increasing over time?',
    chatQuestionPatchesSymmetrically: 'Are patches present symmetrically?',
    chatQuestionOilySkin: 'Do you have oily skin on the affected area?',
    chatQuestionItchyBlisters: 'Do you have itchy fluid-filled blisters?',
    chatQuestionThickScalyPatches: 'Are there thick scaly patches?',
    chatQuestionRedInflamed: 'Is the affected area red and inflamed?',
    chatQuestionItchingBurning: 'Do you have itching or burning?',
    chatQuestionFeverRash: 'Do you have fever along with the rash?',
    chatQuestionChangingMoles: 'Are there changing moles or new growths?',
    chatQuestionBlackheadsWhiteheads: 'Do you notice blackheads or whiteheads?',
    chatQuestionHairLoss: 'Is there hair loss in the affected area?',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    proTipsForBestResults: 'Pro Tips for Best Results',
    faqTip1: 'Use this app as educational guidance, not a diagnostic decision tool',
    faqTip2: 'If symptoms worsen, book an in-person dermatologist consultation',
    faqTip3: 'Keep a timeline of symptom changes to share with your doctor',
    faqTip4: 'Always follow up with a healthcare professional for diagnosis',
    faqFallbackQ1: 'How accurate is this AI diagnosis?',
    faqFallbackA1: 'Our AI model achieves approximately 85-90% accuracy. However, always consult a dermatologist for proper evaluation.',
    faqFallbackQ2: 'What types of skin conditions can this detect?',
    faqFallbackA2: 'Currently: Acne, Chickenpox, Healthy Skin, Psoriasis, Skin Cancer, and Vitiligo.',
    faqFallbackQ3: 'Does this app provide diagnosis?',
    faqFallbackA3: 'No. Diagnostic features are removed. Use this app for educational content and nearby dermatologist discovery.',
    footerAboutTitle: 'About',
    footerAboutText: 'Skin health information portal with educational guidance and nearby dermatologist search.',
    footerDisclaimerTitle: 'Disclaimer',
    footerDisclaimerText: 'This tool is for educational purposes only and does not provide diagnosis or treatment. Always consult a qualified dermatologist for medical advice.',
    footerTechnologyTitle: 'Technology',
    footerCopyright: '© 2026 Derma Assist. Built with ❤️ using Deep Learning.',
    conditionsWeCanDetect: 'Conditions We Can Detect',
    severityNoConcern: 'No concern',
    severityLow: 'Low',
    severityMedium: 'Medium',
    severityHigh: 'High',
    acneRecommendation: 'Use gentle skincare products and consult a dermatologist if symptoms persist.',
    chickenpoxRecommendation: 'Keep the skin clean, avoid scratching, and consult a doctor for symptom relief.',
    healthySkinRecommendation: 'Maintain a regular skincare routine and continue healthy habits.',
    psoriasisRecommendation: 'See a dermatologist for treatment options and trigger management.',
    skinCancerRecommendation: 'Seek prompt evaluation by a dermatologist for further testing and care.',
    vitiligoRecommendation: 'Consult a dermatologist for evaluation and management options.',
    geolocationNotSupported: 'Geolocation is not supported by your browser',
    locationAccessDenied: 'Location access denied. Please enable location in your browser.',
    generalHospitalLocator: 'General Hospital Locator',
    dermatologistFinder: 'Dermatologist Finder',
    noDermatologistsFoundHospitalConsultation: 'No dermatologists found - here are nearby hospitals for medical consultation',
    findSpecializedDermatologists: 'Find specialized dermatologists near your location',
    step5Of5: 'STEP 5 of 5',
    locatingMedicalFacilities: 'Locating medical facilities...',
    pleaseAllowGeolocationAccess: 'Please allow geolocation access',
    tryAgain: 'Try Again',
    noDermatologistsAvailable: 'No Dermatologists Available',
    pleaseVisitNearbyHospital: 'Please visit a nearby general hospital for professional skin disease consultation and treatment.',
    openInGoogleMaps: 'Open in Google Maps',
    resultsFoundTemplate: '✓ {count} {placeType} Found',
    hospitalPlural: 'Hospital(s)',
    dermatologistPlural: 'Dermatologist(s)',
    noResultsFoundNearby: 'No results found nearby',
    available: 'Available',
    limited: 'Limited',
    nearbyDermatologists: 'Nearby Dermatologists',
    hospitalsAndMedicalCenters: 'Hospitals & Medical Centers',
    directions: 'Directions',
    mapView: 'Map View',
    mapTipPrefix: 'Map Tip',
    mapTip: 'Click on markers to see details, then click "Get Directions" to navigate to the location',
    tellYourDoctor: 'Tell Your Doctor',
    emergencySigns: 'Emergency Signs',
    yourLocation: 'Your Location',
    getDirections: 'Get Directions',
  },
  ta: {
    // Tamil
    appName: 'SkinAI கண்டறிதல்',
    poweredBy: 'டீப் லேர்னிங் மூலம் இயக்கப்படுகிறது',
    home: 'முகப்பு',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    about: 'எங்களைப் பற்றி',
    heroTitle: 'AI-இயக்கப்படும் தோல் நோய் கண்டறிதல்',
    heroSubtitle: 'ஒரு படத்தை பதிவேற்றவும், எங்கள் AI உதவியாளர் விரைவான நோயறிதலுக்கு உங்களை வழிநடத்தும். மிகவும் துல்லியமான முடிவுகளுக்கு சில கேள்விகளுக்கு பதிலளிக்கவும்.',
    smartAssistant: 'ஸ்மார்ட் உதவியாளர்',
    imageOnly: 'படம் மட்டும்',
    symptomsOnly: 'அறிகுறிகள் மட்டும்',
    welcomeMessage: '👋 வணக்கம்! நான் உங்கள் தோல் ஆரோக்கிய உதவியாளர். பாதிக்கப்பட்ட தோல் பகுதியின் படத்தை பதிவேற்றவும்.',
    uploadImage: 'படம் பதிவேற்று',
    takePhoto: 'புகைப்படம் எடு',
    chooseFile: 'கோப்பைத் தேர்ந்தெடுக்கவும்',
    analyzing: 'உங்கள் படத்தை பகுப்பாய்வு செய்கிறது... காத்திருக்கவும்.',
    imageReceived: '✅ படம் பெறப்பட்டது! துல்லியமான நோயறிதலுக்கு சில கேள்விகளுக்கு பதிலளிக்கவும்.',
    connectionError: '❌ இணைப்பு பிழை. சேவையகம் இயங்குகிறதா என்பதை உறுதிசெய்து மீண்டும் முயற்சிக்கவும்.',
    analysisError: '❌ மன்னிக்கவும், படத்தை பகுப்பாய்வு செய்வதில் பிழை. மீண்டும் முயற்சிக்கவும்.',
    yes: 'ஆம்',
    no: 'இல்லை',
    uploadTitle: 'படம் பதிவேற்று',
    clickToUpload: 'பதிவேற்ற கிளிக் செய்யவும்',
    orDragDrop: 'அல்லது இழுத்து விடவும்',
    fileTypes: 'PNG, JPG, JPEG (அதிகபட்சம் 10MB)',
    analyzeImage: 'படத்தை பகுப்பாய்வு செய்',
    analyzingBtn: 'பகுப்பாய்வு செய்கிறது...',
    tipsTitle: 'சிறந்த முடிவுகளுக்கான குறிப்புகள்',
    tip1: 'தெளிவான, நன்கு வெளிச்சமான புகைப்படங்களைப் பயன்படுத்தவும்',
    tip2: 'பாதிக்கப்பட்ட தோல் பகுதியில் கவனம் செலுத்தவும்',
    tip3: 'மங்கலான அல்லது தொலைவிலிருந்து எடுத்த படங்களைத் தவிர்க்கவும்',
    tip4: 'தோல் படங்களை மட்டும் சேர்க்கவும்',
    conditionsTitle: 'நாங்கள் கண்டறியக்கூடிய நிலைகள்',
    learnMore: 'மேலும் அறிய',
    symptoms: 'பொதுவான அறிகுறிகள்',
    causes: 'காரணங்கள்',
    prevalence: 'பரவல்',
    severity: 'தீவிரம்',
    close: 'மூடு',
    acne: 'முகப்பரு',
    acneDesc: 'பருக்கள், கரும்புள்ளிகள், வெண்புள்ளிகள்',
    chickenpox: 'சின்னம்மை',
    chickenpoxDesc: 'அரிப்பு கொப்புளங்கள், காய்ச்சல், தடிப்பு',
    healthySkin: 'ஆரோக்கியமான தோல்',
    healthySkinDesc: 'இயல்பான, ஆரோக்கியமான தோற்றம்',
    psoriasis: 'சொரியாசிஸ்',
    psoriasisDesc: 'சிவப்பு திட்டுகள், வெள்ளி செதில்கள்',
    skinCancer: 'தோல் புற்றுநோய்',
    skinCancerDesc: 'மாறும் மச்சங்கள், புதிய வளர்ச்சிகள்',
    vitiligo: 'வெண்குஷ்டம்',
    vitiligoDesc: 'வெள்ளை திட்டுகள், நிறமிழப்பு',
    cameraTitle: 'புகைப்படம் எடு',
    switchCamera: 'கேமரா மாற்று',
    capture: 'படமெடு',
    retake: 'மீண்டும் எடு',
    usePhoto: 'புகைப்படத்தைப் பயன்படுத்து',
    cameraError: 'கேமராவை அணுக முடியவில்லை. அனுமதிகளை சரிபார்க்கவும்.',
    invalidFileType: 'தவறான கோப்பு வகை. JPG, PNG அல்லது WEBP படங்களை பதிவேற்றவும்.',
    fileTooLarge: 'கோப்பு மிகப் பெரியது. அதிகபட்ச அளவு 10MB.',
    imageTooSmall: 'படம் மிகச் சிறியது. தெளிவான, பெரிய படத்தை பதிவேற்றவும்.',
    invalidImage: 'படத்தை ஏற்ற முடியவில்லை. வேறு கோப்பை முயற்சிக்கவும்.',
    clearImage: 'படத்தை அழி',
    clearAndTryAgain: 'அழித்து மீண்டும் முயற்சிக்கவும்',
    results: 'முடிவுகள்',
    confidence: 'நம்பகத்தன்மை',
    recommendation: 'பரிந்துரை',
    disclaimer: 'மறுப்பு: இது மருத்துவ நோயறிதல் அல்ல. சுகாதார நிபுணரை அணுகவும்.',
    footerText: '© 2026 SkinAI கண்டறிதல். கல்வி நோக்கங்களுக்கு மட்டும்.',
    privacyNote: 'உங்கள் படங்கள் பாதுகாப்பாக செயலாக்கப்படுகின்றன, சேமிக்கப்படுவதில்லை.',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    heroBadge: 'AI-இயக்கப்படும் கண்டறிதல்',
    heroDetail: 'எங்கள் மேம்பட்ட அமைப்பு YOLO கண்டறிதல், EfficientNetB3 வகைப்படுத்தல் மற்றும் அறிகுறி கேள்வி-பதில் மூலம் விரைவான ஆரம்ப பகுப்பாய்வை வழங்குகிறது.',
    pleaseUploadImageFirst: 'முதலில் ஒரு படத்தை பதிவேற்றவும் அல்லது பிடிக்கவும்.',
    imageAnalysisFailed: 'படத்தை பகுப்பாய்வு செய்ய முடியவில்லை.',
    uploadOrCapture: 'பதிவேற்று அல்லது படமெடு',
    uploadOrCaptureSubtitle: 'பகுப்பாய்வுக்காக ஒரு படத்தைத் தேர்ந்தெடுக்கவும்',
    dropYourSkinImageHere: 'உங்கள் தோல் படத்தை இங்கே விடவும்',
    useOneOfButtonsBelow: 'அல்லது கீழே உள்ள பட்டன்களில் ஒன்றைப் பயன்படுத்தவும்',
    startingCamera: 'கேமராவைத் தொடங்குகிறது...',
    initializingCamera: 'கேமராவைத் தயார் செய்கிறது...',
    cancel: 'ரத்து செய்',
    removeImage: 'படத்தை நீக்கு',
    imageReadyForAnalysis: 'படம் பகுப்பாய்வுக்கு தயாராக உள்ளது',
    imageRejected: 'தவறான படம்',
    pleaseUploadValidImage: 'தயவுசெய்து செல்லுபடியாகும் படத்தை பதிவேற்றவும்',
    validationFailedPrefix: 'சரிபார்ப்பு தோல்வி:',
    imageDoesNotMeetRequirements: 'படம் தேவைகளை பூர்த்தி செய்யவில்லை',
    failedToValidateImage: 'படத்தை சரிபார்க்க முடியவில்லை',
    pleaseSelectImageFile: 'தயவுசெய்து ஒரு படம் கோப்பைத் தேர்ந்தெடுக்கவும்.',
    cameraFailedPrefix: 'கேமரா தோல்வி',
    cameraNotSupported: 'இந்த உலாவியில் கேமரா ஆதரவு இல்லை',
    cameraInitializationFailed: 'கேமரா துவக்கம் தோல்வியடைந்தது',
    videoElementNotFound: 'வீடியோ உறுப்பு கிடைக்கவில்லை. புதுப்பித்து மீண்டும் முயற்சிக்கவும்.',
    cameraPermissionDenied: 'கேமரா அனுமதி மறுக்கப்பட்டது. உலாவி அமைப்புகளில் அனுமதி வழங்கவும்.',
    noCameraDeviceFound: 'இந்த சாதனத்தில் கேமரா இல்லை.',
    cameraAlreadyInUse: 'கேமரா ஏற்கனவே பயன்பாட்டில் உள்ளது. கேமராவைப் பயன்படுத்தும் மற்ற பயன்பாடுகளை மூடவும்.',
    cameraNotConfigured: 'கேமரா கிடைக்கவில்லை அல்லது சரியாக அமைக்கப்படவில்லை.',
    cameraNotSupportedBrowser: 'உங்கள் உலாவி கேமரா அணுகலை ஆதரிக்கவில்லை. Chrome, Firefox அல்லது Edge முயற்சிக்கவும்.',
    cameraStreamInitializationFailedHelp: 'கேமரா ஸ்ட்ரீம் துவக்கம் தோல்வியடைந்தது. பக்கத்தைப் புதுப்பித்து மீண்டும் முயற்சிக்கவும்.',
    unknownCameraError: 'அறியப்படாத பிழை ஏற்பட்டது.',
    cameraReferenceError: 'கேமரா குறிப்பு பிழை. புதுப்பித்து மீண்டும் முயற்சிக்கவும்.',
    cameraStreamNotReady: 'கேமரா ஸ்ட்ரீம் இன்னும் தயாராக இல்லை. சிறிது நேரம் காத்திருந்து மீண்டும் முயற்சிக்கவும்.',
    failedToCaptureImage: 'படத்தை பிடிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    validatingImageQuality: 'படத் தரத்தை சரிபார்க்கிறது...',
    imageAppearsBlurry: 'படம் மங்கலாக உள்ளது (மதிப்பெண்: {score}%). மேலும் தெளிவான படத்தை எடுக்கவும்.',
    noSkinDetected: 'படத்தில் தோல் கண்டறியப்படவில்லை (தோல் நிறம் {percent}% மட்டும் கண்டறியப்பட்டது). தோல் தெளிவாக தெரியும் படத்தை வழங்கவும்.',
    imageAppearsShaky: 'படம் குலுங்கியதாக அல்லது motion blur உடன் உள்ளது. மேலும் நிலையான படத்தைப் பிடித்து மீண்டும் முயற்சிக்கவும்.',
    imageResolutionLow: 'பட தீர்மானம் குறைவாக உள்ளது ({width}x{height}). சிறந்த முடிவுகளுக்கு அதிக தீர்மான படம் பயன்படுத்தவும்.',
    failedToReadImageFile: 'படக் கோப்பை படிக்க முடியவில்லை',
    symptomAssessment: 'அறிகுறி மதிப்பாய்வு',
    answerQuestionsToRefineDiagnosis: 'உங்கள் நோயறிதலை மேம்படுத்த சில விரைவான கேள்விகளுக்கு பதிலளிக்கவும்',
    step3Of5: 'படி 3 / 5',
    helpRefineDiagnosis: 'அறிகுறி தொடர்பான கேள்விகளுக்கு பதிலளித்து நோயறிதலை மேம்படுத்த உதவுங்கள்',
    loadingQuestions: 'கேள்விகள் ஏற்றப்படுகிறது...',
    startAssessment: 'மதிப்பாய்வைத் தொடங்கு',
    tipAnswerQuestions: 'குறிப்பு: உங்கள் அறிகுறிகள் அல்லது பார்வைகளின் அடிப்படையில் ஒவ்வொரு கேள்விக்கும் பதிலளிக்கவும்',
    computingFinalDiagnosis: 'இறுதி நோயறிதலை கணக்கிடுகிறது...',
    getFinalDiagnosis: 'இறுதி நோயறிதலைப் பெறுங்கள்',
    failedToLoadQuestions: 'கேள்விகளை ஏற்ற முடியவில்லை.',
    failedToComputeFinalDecision: 'இறுதி முடிவை கணக்கிட முடியவில்லை',
    finalDiagnosis: 'இறுதி நோயறிதல்',
    basedOnImageAnalysisAndSymptoms: 'பட பகுப்பாய்வு மற்றும் அறிகுறி மதிப்பாய்வின் அடிப்படையில்',
    step4Of5: 'படி 4 / 5',
    confidenceScore: 'நம்பக மதிப்பெண்',
    methodologyAiSymptoms: 'முறை',
    methodologyAiSymptomsValue: 'AI + அறிகுறிகள்',
    analysisVisualization: 'பகுப்பாய்வு காட்சிப்படுத்தல்',
    originalImage: 'மூல படம்',
    yoloDetectionRedBoxes: 'YOLO கண்டறிதல் (சிவப்பு பெட்டிகள்)',
    lesionSegmentation: 'காயப் பகுதி துண்டாக்கல்',
    loadingImage: 'படம் ஏற்றப்படுகிறது...',
    symptomQuestionsAnalyzed: 'அறிகுறி கேள்விகள் பகுப்பாய்வு செய்யப்பட்டன',
    chatQuestionWhitePatches: 'தெளிவாக வெள்ளை திட்டுகள் தெரிகிறதா?',
    chatQuestionPatchesIncreasing: 'திட்டுகள் காலப்போக்கில் அதிகரிக்கிறதா?',
    chatQuestionPatchesSymmetrically: 'திட்டுகள் சமச்சீராக உள்ளனவா?',
    chatQuestionOilySkin: 'பாதிக்கப்பட்ட பகுதியில் எண்ணெய் போன்ற தோல் உள்ளதா?',
    chatQuestionItchyBlisters: 'அரிப்பு உள்ள திரவ நிரம்பிய கொப்புளங்கள் உள்ளனவா?',
    chatQuestionThickScalyPatches: 'தடிமனான செதில் போன்ற திட்டுகள் உள்ளனவா?',
    chatQuestionRedInflamed: 'பாதிக்கப்பட்ட பகுதி சிவப்பாகவும் வீக்கமுடனும் உள்ளதா?',
    chatQuestionItchingBurning: 'அரிப்பு அல்லது எரிச்சல் உள்ளதா?',
    chatQuestionFeverRash: 'சொறி உடன் காய்ச்சல் உள்ளதா?',
    chatQuestionChangingMoles: 'மாறும் மச்சங்கள் அல்லது புதிய வளர்ச்சிகள் உள்ளனவா?',
    chatQuestionBlackheadsWhiteheads: 'கரும்புள்ளிகள் அல்லது வெண்புள்ளிகள் காணப்படுகிறதா?',
    chatQuestionHairLoss: 'பாதிக்கப்பட்ட பகுதியில் முடி உதிர்வா உள்ளது?',
    frequentlyAskedQuestions: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    proTipsForBestResults: 'சிறந்த முடிவுகளுக்கான குறிப்புகள்',
    faqTip1: 'இந்த பயன்பாட்டை கல்வி வழிகாட்டியாகப் பயன்படுத்தவும், நோயறிதல் கருவியாக அல்ல',
    faqTip2: 'அறிகுறிகள் மோசமடைந்தால், நேரில் தோல் மருத்துவரை அணுகவும்',
    faqTip3: 'உங்கள் மருத்துவருடன் பகிர симптом மாற்றங்களின் காலவரிசையை வைத்திருங்கள்',
    faqTip4: 'நோயறிதலுக்காக எப்போதும் ஒரு சுகாதார நிபுணரைப் பின்தொடரவும்',
    faqFallbackQ1: 'இந்த AI நோயறிதல் எவ்வளவு துல்லியம்?',
    faqFallbackA1: 'எங்கள் AI மாதிரி சுமார் 85-90% துல்லியத்தை அடைகிறது. இருப்பினும், சரியான மதிப்பீட்டிற்கு எப்போதும் ஒரு தோல் மருத்துவரை அணுகவும்.',
    faqFallbackQ2: 'எந்த வகையான தோல் நிலைகளை இது கண்டறியும்?',
    faqFallbackA2: 'தற்போது: முகப்பரு, சின்னம்மை, ஆரோக்கியமான தோல், சொரியாசிஸ், தோல் புற்றுநோய் மற்றும் வெண்குஷ்டம்.',
    faqFallbackQ3: 'இந்த பயன்பாடு நோயறிதலை வழங்குமா?',
    faqFallbackA3: 'இல்லை. நோயறிதல் அம்சங்கள் நீக்கப்பட்டுள்ளன. கல்வி உள்ளடக்கம் மற்றும் அருகிலுள்ள தோல் மருத்துவர் தேடலுக்காக இந்த பயன்பாட்டைப் பயன்படுத்தவும்.',
    footerAboutTitle: 'பற்றி',
    footerAboutText: 'கல்வி வழிகாட்டல் மற்றும் அருகிலுள்ள தோல் மருத்துவர் தேடலுடன் கூடிய தோல் ஆரோக்கிய தகவல் தளம்.',
    footerDisclaimerTitle: 'மறுப்பு',
    footerDisclaimerText: 'இந்த கருவி கல்வி நோக்கங்களுக்காக மட்டுமே, நோயறிதல் அல்லது சிகிச்சையை வழங்காது. மருத்துவ ஆலோசனைக்காக தகுதியான தோல் மருத்துவரை எப்போதும் அணுகவும்.',
    footerTechnologyTitle: 'தொழில்நுட்பம்',
    footerCopyright: '© 2026 Derma Assist. Deep Learning பயன்படுத்தி உருவாக்கப்பட்டது.',
    conditionsWeCanDetect: 'நாங்கள் கண்டறியக்கூடிய நிலைகள்',
    severityNoConcern: 'கவலை இல்லை',
    severityLow: 'குறைவு',
    severityMedium: 'நடுத்தரம்',
    severityHigh: 'அதிகம்',
    acneRecommendation: 'மென்மையான சரும பராமரிப்பு பொருட்களைப் பயன்படுத்தி, அறிகுறிகள் நீடித்தால் தோல் மருத்துவரை அணுகவும்.',
    chickenpoxRecommendation: 'தோலை சுத்தமாக வைத்துக் கொள்ளவும், கீற வேண்டாம், அறிகுறி நிவாரணத்திற்காக மருத்துவரை அணுகவும்.',
    healthySkinRecommendation: 'வழக்கமான சரும பராமரிப்பு முறையைத் தொடர்ந்து நல்ல பழக்கங்களைப் பேணவும்.',
    psoriasisRecommendation: 'சிகிச்சை விருப்பங்கள் மற்றும் தூண்டுதல்களை நிர்வகிக்க தோல் மருத்துவரை அணுகவும்.',
    skinCancerRecommendation: 'மேலும் பரிசோதனை மற்றும் பராமரிப்புக்காக தோல் மருத்துவரை விரைவில் அணுகவும்.',
    vitiligoRecommendation: 'மதிப்பீடு மற்றும் மேலாண்மை விருப்பங்களுக்காக தோல் மருத்துவரை அணுகவும்.',
    geolocationNotSupported: 'உங்கள் உலாவி geolocation-ஐ ஆதரிக்கவில்லை',
    locationAccessDenied: 'இருப்பிட அணுகல் மறுக்கப்பட்டது. உலாவியில் இடம் அனுமதியை இயக்கவும்.',
    generalHospitalLocator: 'பொது மருத்துவமனை கண்டுபிடிப்பான்',
    dermatologistFinder: 'தோல் மருத்துவர் கண்டுபிடிப்பான்',
    noDermatologistsFoundHospitalConsultation: 'தோல் மருத்துவர்கள் கிடைக்கவில்லை - மருத்துவ ஆலோசனைக்காக அருகிலுள்ள மருத்துவமனைகள் இங்கே',
    findSpecializedDermatologists: 'உங்கள் இருப்பிடத்திற்கு அருகிலுள்ள சிறப்பு தோல் மருத்துவர்களைக் கண்டறியவும்',
    step5Of5: 'படி 5 / 5',
    locatingMedicalFacilities: 'மருத்துவ வசதிகளை கண்டறிகிறது...',
    pleaseAllowGeolocationAccess: 'geolocation அணுகலை அனுமதிக்கவும்',
    tryAgain: 'மீண்டும் முயற்சிக்கவும்',
    noDermatologistsAvailable: 'தோல் மருத்துவர் கிடைக்கவில்லை',
    pleaseVisitNearbyHospital: 'தொழில்முறை தோல் நோய் ஆலோசனை மற்றும் சிகிச்சைக்காக அருகிலுள்ள பொது மருத்துவமனைக்குச் செல்லவும்.',
    openInGoogleMaps: 'Google Maps-இல் திறக்கவும்',
    resultsFoundTemplate: '✓ {count} {placeType} கண்டறியப்பட்டது',
    hospitalPlural: 'மருத்துவமனைகள்',
    dermatologistPlural: 'தோல் மருத்துவர்கள்',
    noResultsFoundNearby: 'அருகில் முடிவுகள் இல்லை',
    available: 'கிடைக்கிறது',
    limited: 'குறைவு',
    nearbyDermatologists: 'அருகிலுள்ள தோல் மருத்துவர்கள்',
    hospitalsAndMedicalCenters: 'மருத்துவமனைகள் & மருத்துவ மையங்கள்',
    directions: 'வழிகள்',
    mapView: 'வரைபடக் காட்சி',
    mapTipPrefix: 'வரைபட குறிப்பு',
    mapTip: 'விவரங்களைப் பார்க்க குறிகளில் கிளிக் செய்யவும், பின்னர் இருப்பிடத்திற்குச் செல்ல "Get Directions"-ஐ கிளிக் செய்யவும்',
    tellYourDoctor: 'உங்கள் மருத்துவரிடம் சொல்லுங்கள்',
    emergencySigns: 'அவசர அறிகுறிகள்',
    yourLocation: 'உங்கள் இருப்பிடம்',
    getDirections: 'வழிகளைப் பெறுங்கள்',
  },
  hi: {
    // Hindi
    appName: 'SkinAI डिटेक्टर',
    poweredBy: 'डीप लर्निंग द्वारा संचालित',
    home: 'होम',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    about: 'हमारे बारे में',
    heroTitle: 'AI-संचालित त्वचा रोग पहचान',
    heroSubtitle: 'एक छवि अपलोड करें और हमारे AI सहायक को त्वरित निदान में आपका मार्गदर्शन करने दें। सबसे सटीक परिणामों के लिए कुछ प्रश्नों के उत्तर दें।',
    smartAssistant: 'स्मार्ट सहायक',
    imageOnly: 'केवल छवि',
    symptomsOnly: 'केवल लक्षण',
    welcomeMessage: '👋 नमस्ते! मैं आपका त्वचा स्वास्थ्य सहायक हूं। विश्लेषण शुरू करने के लिए कृपया प्रभावित त्वचा क्षेत्र की एक छवि अपलोड करें।',
    uploadImage: 'छवि अपलोड करें',
    takePhoto: 'फोटो लें',
    chooseFile: 'फ़ाइल चुनें',
    analyzing: 'आपकी छवि का विश्लेषण किया जा रहा है... कृपया प्रतीक्षा करें।',
    imageReceived: '✅ छवि प्राप्त हुई! मैंने आपकी छवि का विश्लेषण कर लिया है। अब मुझे सबसे सटीक निदान प्रदान करने के लिए आपके लक्षणों के बारे में कुछ प्रश्न पूछने होंगे।',
    connectionError: '❌ कनेक्शन त्रुटि। कृपया सुनिश्चित करें कि सर्वर चल रहा है और पुनः प्रयास करें।',
    analysisError: '❌ क्षमा करें, छवि का विश्लेषण करने में त्रुटि हुई। कृपया पुनः प्रयास करें।',
    yes: 'हाँ',
    no: 'नहीं',
    uploadTitle: 'छवि अपलोड करें',
    clickToUpload: 'अपलोड करने के लिए क्लिक करें',
    orDragDrop: 'या खींचें और छोड़ें',
    fileTypes: 'PNG, JPG, JPEG (अधिकतम 10MB)',
    analyzeImage: 'छवि का विश्लेषण करें',
    analyzingBtn: 'विश्लेषण हो रहा है...',
    tipsTitle: 'सर्वोत्तम परिणामों के लिए सुझाव',
    tip1: 'स्पष्ट, अच्छी रोशनी वाली तस्वीरें उपयोग करें',
    tip2: 'प्रभावित त्वचा क्षेत्र पर फोकस करें',
    tip3: 'धुंधली या दूर की तस्वीरों से बचें',
    tip4: 'केवल त्वचा की छवियां शामिल करें',
    conditionsTitle: 'हम जिन स्थितियों का पता लगा सकते हैं',
    learnMore: 'और जानें',
    symptoms: 'सामान्य लक्षण',
    causes: 'कारण',
    prevalence: 'व्यापकता',
    severity: 'गंभीरता',
    close: 'बंद करें',
    acne: 'मुँहासे',
    acneDesc: 'फुंसी, ब्लैकहेड्स, व्हाइटहेड्स',
    chickenpox: 'चिकनपॉक्स',
    chickenpoxDesc: 'खुजली वाले छाले, बुखार, दाने',
    healthySkin: 'स्वस्थ त्वचा',
    healthySkinDesc: 'सामान्य, स्वस्थ दिखावट',
    psoriasis: 'सोरायसिस',
    psoriasisDesc: 'लाल धब्बे, चांदी जैसी पपड़ी',
    skinCancer: 'त्वचा कैंसर',
    skinCancerDesc: 'बदलते तिल, नई वृद्धि',
    vitiligo: 'विटिलिगो',
    vitiligoDesc: 'सफेद धब्बे, रंग का नुकसान',
    cameraTitle: 'फोटो लें',
    switchCamera: 'कैमरा बदलें',
    capture: 'कैप्चर',
    retake: 'फिर से लें',
    usePhoto: 'फोटो उपयोग करें',
    cameraError: 'कैमरा एक्सेस नहीं हो पा रहा। कृपया अनुमतियां जांचें।',
    invalidFileType: 'अमान्य फ़ाइल प्रकार। कृपया JPG, PNG या WEBP छवियां अपलोड करें।',
    fileTooLarge: 'फ़ाइल बहुत बड़ी है। अधिकतम आकार 10MB है।',
    imageTooSmall: 'छवि बहुत छोटी है। कृपया एक स्पष्ट, बड़ी छवि अपलोड करें।',
    invalidImage: 'छवि लोड नहीं हो सकी। कृपया दूसरी फ़ाइल आज़माएं।',
    clearImage: 'छवि साफ़ करें',
    clearAndTryAgain: 'साफ़ करें और फिर से प्रयास करें',
    results: 'परिणाम',
    confidence: 'विश्वास',
    recommendation: 'सिफारिश',
    disclaimer: 'अस्वीकरण: यह चिकित्सा निदान नहीं है। कृपया स्वास्थ्य पेशेवर से परामर्श करें।',
    footerText: '© 2026 SkinAI डिटेक्टर। केवल शैक्षिक उद्देश्यों के लिए।',
    privacyNote: 'आपकी छवियां सुरक्षित रूप से संसाधित की जाती हैं और संग्रहीत नहीं की जातीं।',
    selectLanguage: 'भाषा चुनें',
    heroBadge: 'AI-संचालित पहचान',
    heroDetail: 'हमारी उन्नत प्रणाली YOLO पहचान, EfficientNetB3 वर्गीकरण और लक्षण प्रश्नोत्तर का उपयोग करके तेज़ प्रारंभिक विश्लेषण प्रदान करती है।',
    pleaseUploadImageFirst: 'कृपया पहले एक छवि अपलोड या कैप्चर करें।',
    imageAnalysisFailed: 'छवि विश्लेषण विफल रहा।',
    uploadOrCapture: 'अपलोड या कैप्चर करें',
    uploadOrCaptureSubtitle: 'विश्लेषण के लिए एक छवि चुनें',
    dropYourSkinImageHere: 'अपनी त्वचा की छवि यहाँ छोड़ें',
    useOneOfButtonsBelow: 'या नीचे दिए गए बटनों में से किसी एक का उपयोग करें',
    startingCamera: 'कैमरा शुरू हो रहा है...',
    initializingCamera: 'कैमरा प्रारंभ हो रहा है...',
    cancel: 'रद्द करें',
    removeImage: 'छवि हटाएं',
    imageReadyForAnalysis: 'छवि विश्लेषण के लिए तैयार है',
    imageRejected: 'अमान्य छवि',
    pleaseUploadValidImage: 'कृपया एक वैध छवि अपलोड करें',
    validationFailedPrefix: 'सत्यापन विफल:',
    imageDoesNotMeetRequirements: 'छवि आवश्यकताओं को पूरा नहीं करती',
    failedToValidateImage: 'छवि सत्यापित नहीं की जा सकी',
    pleaseSelectImageFile: 'कृपया एक छवि फ़ाइल चुनें।',
    cameraFailedPrefix: 'कैमरा विफल',
    cameraNotSupported: 'इस ब्राउज़र में कैमरा समर्थित नहीं है',
    cameraInitializationFailed: 'कैमरा प्रारंभिकरण विफल',
    videoElementNotFound: 'वीडियो तत्व नहीं मिला। कृपया रीफ़्रेश करके फिर प्रयास करें।',
    cameraPermissionDenied: 'कैमरा अनुमति अस्वीकार कर दी गई। कृपया ब्राउज़र सेटिंग्स में अनुमति दें।',
    noCameraDeviceFound: 'इस डिवाइस पर कोई कैमरा नहीं मिला।',
    cameraAlreadyInUse: 'कैमरा पहले से उपयोग में है। कैमरा उपयोग करने वाले अन्य ऐप बंद करें।',
    cameraNotConfigured: 'कैमरा उपलब्ध नहीं है या सही तरह से कॉन्फ़िगर नहीं है।',
    cameraNotSupportedBrowser: 'आपका ब्राउज़र कैमरा एक्सेस का समर्थन नहीं करता। Chrome, Firefox या Edge आज़माएं।',
    cameraStreamInitializationFailedHelp: 'कैमरा स्ट्रीम प्रारंभ करने में विफल। कृपया पेज रीफ़्रेश करके फिर प्रयास करें।',
    unknownCameraError: 'अज्ञात त्रुटि हुई।',
    cameraReferenceError: 'कैमरा संदर्भ त्रुटि। कृपया रीफ़्रेश करके फिर प्रयास करें।',
    cameraStreamNotReady: 'कैमरा स्ट्रीम अभी तैयार नहीं है। कृपया थोड़ा इंतज़ार करें और फिर प्रयास करें।',
    failedToCaptureImage: 'छवि कैप्चर नहीं की जा सकी। कृपया फिर प्रयास करें।',
    validatingImageQuality: 'छवि गुणवत्ता जाँची जा रही है...',
    imageAppearsBlurry: 'छवि धुंधली लग रही है (स्कोर: {score}%). कृपया और स्पष्ट छवि लें।',
    noSkinDetected: 'छवि में त्वचा नहीं मिली (केवल {percent}% त्वचा टोन मिला)। कृपया त्वचा स्पष्ट दिखाने वाली छवि दें।',
    imageAppearsShaky: 'छवि में कंपन या motion blur है। कृपया अधिक स्थिर कैप्चर के साथ फिर प्रयास करें।',
    imageResolutionLow: 'छवि का रिज़ॉल्यूशन कम है ({width}x{height}). बेहतर परिणाम के लिए उच्च रिज़ॉल्यूशन छवि का उपयोग करें।',
    failedToReadImageFile: 'छवि फ़ाइल पढ़ी नहीं जा सकी',
    symptomAssessment: 'लक्षण मूल्यांकन',
    answerQuestionsToRefineDiagnosis: 'अपने निदान को बेहतर करने के लिए कुछ त्वरित प्रश्नों के उत्तर दें',
    step3Of5: 'चरण 3 / 5',
    helpRefineDiagnosis: 'लक्षण-संबंधी प्रश्नों के उत्तर देकर निदान को बेहतर बनाने में मदद करें',
    loadingQuestions: 'प्रश्न लोड हो रहे हैं...',
    startAssessment: 'मूल्यांकन शुरू करें',
    tipAnswerQuestions: 'सुझाव: अपने लक्षणों या अवलोकनों के आधार पर हर प्रश्न का उत्तर दें',
    computingFinalDiagnosis: 'अंतिम निदान तैयार किया जा रहा है...',
    getFinalDiagnosis: 'अंतिम निदान प्राप्त करें',
    failedToLoadQuestions: 'प्रश्न लोड नहीं किए जा सके।',
    failedToComputeFinalDecision: 'अंतिम निर्णय की गणना नहीं की जा सकी',
    finalDiagnosis: 'अंतिम निदान',
    basedOnImageAnalysisAndSymptoms: 'छवि विश्लेषण और लक्षण मूल्यांकन के आधार पर',
    step4Of5: 'चरण 4 / 5',
    confidenceScore: 'विश्वास स्कोर',
    methodologyAiSymptoms: 'विधि',
    methodologyAiSymptomsValue: 'AI + लक्षण',
    analysisVisualization: 'विश्लेषण दृश्य',
    originalImage: 'मूल छवि',
    yoloDetectionRedBoxes: 'YOLO पहचान (लाल बॉक्स)',
    lesionSegmentation: 'घाव विभाजन',
    loadingImage: 'छवि लोड हो रही है...',
    symptomQuestionsAnalyzed: 'लक्षण प्रश्नों का विश्लेषण किया गया',
    chatQuestionWhitePatches: 'क्या आपको स्पष्ट सफेद धब्बे दिखते हैं?',
    chatQuestionPatchesIncreasing: 'क्या समय के साथ धब्बे बढ़ रहे हैं?',
    chatQuestionPatchesSymmetrically: 'क्या धब्बे सममित रूप से मौजूद हैं?',
    chatQuestionOilySkin: 'क्या प्रभावित क्षेत्र में त्वचा तैलीय है?',
    chatQuestionItchyBlisters: 'क्या आपको खुजली वाले तरल भरे छाले हैं?',
    chatQuestionThickScalyPatches: 'क्या मोटे पपड़ीदार धब्बे हैं?',
    chatQuestionRedInflamed: 'क्या प्रभावित क्षेत्र लाल और सूजा हुआ है?',
    chatQuestionItchingBurning: 'क्या खुजली या जलन है?',
    chatQuestionFeverRash: 'क्या दाने के साथ बुखार है?',
    chatQuestionChangingMoles: 'क्या तिल बदल रहे हैं या नई वृद्धि है?',
    chatQuestionBlackheadsWhiteheads: 'क्या आपको ब्लैकहेड्स या व्हाइटहेड्स दिखते हैं?',
    chatQuestionHairLoss: 'क्या प्रभावित क्षेत्र में बाल झड़ रहे हैं?',
    frequentlyAskedQuestions: 'अक्सर पूछे जाने वाले प्रश्न',
    proTipsForBestResults: 'सर्वोत्तम परिणामों के लिए प्रो टिप्स',
    faqTip1: 'इस ऐप का उपयोग शैक्षिक मार्गदर्शन के रूप में करें, निदान निर्णय उपकरण के रूप में नहीं',
    faqTip2: 'यदि लक्षण बिगड़ें, तो व्यक्तिगत रूप से त्वचा विशेषज्ञ से मिलें',
    faqTip3: 'अपने डॉक्टर के साथ साझा करने के लिए लक्षण परिवर्तनों की समयरेखा रखें',
    faqTip4: 'निदान के लिए हमेशा स्वास्थ्य पेशेवर के साथ फॉलो-अप करें',
    faqFallbackQ1: 'यह AI निदान कितना सटीक है?',
    faqFallbackA1: 'हमारा AI मॉडल लगभग 85-90% सटीकता प्राप्त करता है। हालांकि, उचित मूल्यांकन के लिए हमेशा त्वचा विशेषज्ञ से सलाह लें।',
    faqFallbackQ2: 'यह किन त्वचा स्थितियों का पता लगा सकता है?',
    faqFallbackA2: 'वर्तमान में: मुंहासे, चिकनपॉक्स, स्वस्थ त्वचा, सोरायसिस, त्वचा कैंसर, और विटिलिगो।',
    faqFallbackQ3: 'क्या यह ऐप निदान प्रदान करता है?',
    faqFallbackA3: 'नहीं। निदान सुविधाएँ हटा दी गई हैं। इस ऐप का उपयोग शैक्षिक सामग्री और पास के त्वचा विशेषज्ञ खोज के लिए करें।',
    footerAboutTitle: 'के बारे में',
    footerAboutText: 'शैक्षिक मार्गदर्शन और पास के त्वचा विशेषज्ञ खोज के साथ त्वचा स्वास्थ्य सूचना पोर्टल।',
    footerDisclaimerTitle: 'अस्वीकरण',
    footerDisclaimerText: 'यह उपकरण केवल शैक्षिक उद्देश्यों के लिए है और निदान या उपचार प्रदान नहीं करता। चिकित्सा सलाह के लिए हमेशा योग्य त्वचा विशेषज्ञ से परामर्श करें।',
    footerTechnologyTitle: 'प्रौद्योगिकी',
    footerCopyright: '© 2026 Derma Assist. Deep Learning का उपयोग करके बनाया गया।',
    conditionsWeCanDetect: 'हम जिन स्थितियों का पता लगा सकते हैं',
    severityNoConcern: 'कोई चिंता नहीं',
    severityLow: 'कम',
    severityMedium: 'मध्यम',
    severityHigh: 'उच्च',
    acneRecommendation: 'हल्के स्किनकेयर उत्पादों का उपयोग करें और यदि लक्षण बने रहें तो त्वचा विशेषज्ञ से सलाह लें।',
    chickenpoxRecommendation: 'त्वचा को साफ रखें, खरोंचने से बचें, और लक्षण राहत के लिए डॉक्टर से सलाह लें।',
    healthySkinRecommendation: 'नियमित स्किनकेयर दिनचर्या बनाए रखें और स्वस्थ आदतें जारी रखें।',
    psoriasisRecommendation: 'उपचार विकल्पों और ट्रिगर प्रबंधन के लिए त्वचा विशेषज्ञ से मिलें।',
    skinCancerRecommendation: 'आगे की जांच और देखभाल के लिए त्वचा विशेषज्ञ से तुरंत मूल्यांकन करवाएं।',
    vitiligoRecommendation: 'मूल्यांकन और प्रबंधन विकल्पों के लिए त्वचा विशेषज्ञ से सलाह लें।',
    geolocationNotSupported: 'आपका ब्राउज़र geolocation का समर्थन नहीं करता',
    locationAccessDenied: 'स्थान एक्सेस अस्वीकृत। कृपया अपने ब्राउज़र में स्थान सक्षम करें।',
    generalHospitalLocator: 'सामान्य अस्पताल लोकेटर',
    dermatologistFinder: 'त्वचा विशेषज्ञ खोजक',
    noDermatologistsFoundHospitalConsultation: 'कोई त्वचा विशेषज्ञ नहीं मिला - चिकित्सा परामर्श के लिए पास के अस्पताल यहाँ हैं',
    findSpecializedDermatologists: 'अपने स्थान के पास विशेष त्वचा विशेषज्ञ खोजें',
    step5Of5: 'चरण 5 / 5',
    locatingMedicalFacilities: 'चिकित्सा सुविधाएँ ढूँढ रहा है...',
    pleaseAllowGeolocationAccess: 'कृपया geolocation एक्सेस अनुमति दें',
    tryAgain: 'फिर से कोशिश करें',
    noDermatologistsAvailable: 'कोई त्वचा विशेषज्ञ उपलब्ध नहीं',
    pleaseVisitNearbyHospital: 'पेशेवर त्वचा रोग परामर्श और उपचार के लिए पास के सामान्य अस्पताल जाएँ।',
    openInGoogleMaps: 'Google Maps में खोलें',
    resultsFoundTemplate: '✓ {count} {placeType} मिला',
    hospitalPlural: 'अस्पताल',
    dermatologistPlural: 'त्वचा विशेषज्ञ',
    noResultsFoundNearby: 'पास में कोई परिणाम नहीं मिला',
    available: 'उपलब्ध',
    limited: 'सीमित',
    nearbyDermatologists: 'पास के त्वचा विशेषज्ञ',
    hospitalsAndMedicalCenters: 'अस्पताल और चिकित्सा केंद्र',
    directions: 'दिशानिर्देश',
    mapView: 'मानचित्र दृश्य',
    mapTipPrefix: 'मानचित्र सुझाव',
    mapTip: 'विवरण देखने के लिए मार्कर पर क्लिक करें, फिर स्थान पर जाने के लिए "Get Directions" पर क्लिक करें',
    tellYourDoctor: 'अपने डॉक्टर को बताएं',
    emergencySigns: 'आपातकालीन संकेत',
    yourLocation: 'आपका स्थान',
    getDirections: 'दिशाएँ प्राप्त करें',
  },
  ml: {
    // Malayalam
    appName: 'SkinAI ഡിറ്റക്ടർ',
    poweredBy: 'ഡീപ് ലേണിംഗ് ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്നു',
    home: 'ഹോം',
    faq: 'പതിവ് ചോദ്യങ്ങൾ',
    about: 'ഞങ്ങളെക്കുറിച്ച്',
    heroTitle: 'AI-പവർഡ് ത്വക്ക് രോഗ കണ്ടെത്തൽ',
    heroSubtitle: 'ഒരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക, ഞങ്ങളുടെ AI അസിസ്റ്റന്റ് വേഗത്തിലുള്ള രോഗനിർണയത്തിലൂടെ നിങ്ങളെ നയിക്കും.',
    smartAssistant: 'സ്മാർട്ട് അസിസ്റ്റന്റ്',
    imageOnly: 'ചിത്രം മാത്രം',
    symptomsOnly: 'ലക്ഷണങ്ങൾ മാത്രം',
    welcomeMessage: '👋 ഹലോ! ഞാൻ നിങ്ങളുടെ ത്വക്ക് ആരോഗ്യ അസിസ്റ്റന്റാണ്. വിശകലനം ആരംഭിക്കാൻ ബാധിത ത്വക്ക് പ്രദേശത്തിന്റെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.',
    uploadImage: 'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    takePhoto: 'ഫോട്ടോ എടുക്കുക',
    chooseFile: 'ഫയൽ തിരഞ്ഞെടുക്കുക',
    analyzing: 'നിങ്ങളുടെ ചിത്രം വിശകലനം ചെയ്യുന്നു... കാത്തിരിക്കുക.',
    imageReceived: '✅ ചിത്രം ലഭിച്ചു! കൃത്യമായ രോഗനിർണയത്തിനായി കുറച്ച് ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകുക.',
    connectionError: '❌ കണക്ഷൻ പിശക്. സെർവർ പ്രവർത്തിക്കുന്നുണ്ടെന്ന് ഉറപ്പാക്കി വീണ്ടും ശ്രമിക്കുക.',
    analysisError: '❌ ക്ഷമിക്കണം, ചിത്രം വിശകലനം ചെയ്യുന്നതിൽ പിശക്. വീണ്ടും ശ്രമിക്കുക.',
    yes: 'അതെ',
    no: 'ഇല്ല',
    uploadTitle: 'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    clickToUpload: 'അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക',
    orDragDrop: 'അല്ലെങ്കിൽ വലിച്ചിടുക',
    fileTypes: 'PNG, JPG, JPEG (പരമാവധി 10MB)',
    analyzeImage: 'ചിത്രം വിശകലനം ചെയ്യുക',
    analyzingBtn: 'വിശകലനം ചെയ്യുന്നു...',
    tipsTitle: 'മികച്ച ഫലങ്ങൾക്കുള്ള നുറുങ്ങുകൾ',
    tip1: 'വ്യക്തമായ, നന്നായി പ്രകാശിതമായ ഫോട്ടോകൾ ഉപയോഗിക്കുക',
    tip2: 'ബാധിത ത്വക്ക് പ്രദേശത്ത് ശ്രദ്ധ കേന്ദ്രീകരിക്കുക',
    tip3: 'മങ്ങിയതോ ദൂരെ നിന്നുള്ളതോ ആയ ഷോട്ടുകൾ ഒഴിവാക്കുക',
    tip4: 'ത്വക്ക് ചിത്രങ്ങൾ മാത്രം ഉൾപ്പെടുത്തുക',
    conditionsTitle: 'ഞങ്ങൾക്ക് കണ്ടെത്താൻ കഴിയുന്ന അവസ്ഥകൾ',
    learnMore: 'കൂടുതൽ അറിയുക',
    symptoms: 'സാധാരണ ലക്ഷണങ്ങൾ',
    causes: 'കാരണങ്ങൾ',
    prevalence: 'വ്യാപനം',
    severity: 'തീവ്രത',
    close: 'അടയ്ക്കുക',
    acne: 'മുഖക്കുരു',
    acneDesc: 'പരുക്കൾ, കറുത്ത പുള്ളികൾ, വെളുത്ത പുള്ളികൾ',
    chickenpox: 'ചിക്കൻപോക്സ്',
    chickenpoxDesc: 'ചൊറിച്ചിലുള്ള കുമിളകൾ, പനി, ചുണങ്ങ്',
    healthySkin: 'ആരോഗ്യകരമായ ത്വക്ക്',
    healthySkinDesc: 'സാധാരണ, ആരോഗ്യകരമായ രൂപം',
    psoriasis: 'സോറിയാസിസ്',
    psoriasisDesc: 'ചുവന്ന പാടുകൾ, വെള്ളി ചെതുമ്പലുകൾ',
    skinCancer: 'ത്വക്ക് കാൻസർ',
    skinCancerDesc: 'മാറുന്ന മറുകുകൾ, പുതിയ വളർച്ചകൾ',
    vitiligo: 'വിറ്റിലിഗോ',
    vitiligoDesc: 'വെളുത്ത പാടുകൾ, നിറം നഷ്ടപ്പെടൽ',
    cameraTitle: 'ഫോട്ടോ എടുക്കുക',
    switchCamera: 'ക്യാമറ മാറ്റുക',
    capture: 'പിടിച്ചെടുക്കുക',
    retake: 'വീണ്ടും എടുക്കുക',
    usePhoto: 'ഫോട്ടോ ഉപയോഗിക്കുക',
    cameraError: 'ക്യാമറ ആക്സസ് ചെയ്യാൻ കഴിയുന്നില്ല. അനുമതികൾ പരിശോധിക്കുക.',
    invalidFileType: 'അസാധുവായ ഫയൽ തരം. JPG, PNG അല്ലെങ്കിൽ WEBP ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുക.',
    fileTooLarge: 'ഫയൽ വളരെ വലുതാണ്. പരമാവധി വലുപ്പം 10MB.',
    imageTooSmall: 'ചിത്രം വളരെ ചെറുതാണ്. കൂടുതൽ വ്യക്തമായ, വലിയ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.',
    invalidImage: 'ചിത്രം ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല. മറ്റൊരു ഫയൽ ശ്രമിക്കുക.',
    clearImage: 'ചിത്രം മായ്ക്കുക',
    clearAndTryAgain: 'മായ്ച്ച് വീണ്ടും ശ്രമിക്കുക',
    results: 'ഫലങ്ങൾ',
    confidence: 'വിശ്വാസ്യത',
    recommendation: 'ശുപാർശ',
    disclaimer: 'നിരാകരണം: ഇത് മെഡിക്കൽ രോഗനിർണയമല്ല. ആരോഗ്യ വിദഗ്ധനെ സമീപിക്കുക.',
    footerText: '© 2026 SkinAI ഡിറ്റക്ടർ. വിദ്യാഭ്യാസ ആവശ്യങ്ങൾക്ക് മാത്രം.',
    privacyNote: 'നിങ്ങളുടെ ചിത്രങ്ങൾ സുരക്ഷിതമായി പ്രോസസ്സ് ചെയ്യുന്നു, സംഭരിക്കുന്നില്ല.',
  },
  te: {
    // Telugu
    appName: 'SkinAI డిటెక్టర్',
    poweredBy: 'డీప్ లెర్నింగ్ ద్వారా ఆధారితం',
    home: 'హోమ్',
    faq: 'తరచుగా అడిగే ప్రశ్నలు',
    about: 'మా గురించి',
    heroTitle: 'AI-ఆధారిత చర్మ వ్యాధి గుర్తింపు',
    heroSubtitle: 'చిత్రాన్ని అప్‌లోడ్ చేయండి, మా AI అసిస్టెంట్ త్వరిత రోగ నిర్ధారణలో మీకు మార్గనిర్దేశం చేస్తుంది.',
    smartAssistant: 'స్మార్ట్ అసిస్టెంట్',
    imageOnly: 'చిత్రం మాత్రమే',
    symptomsOnly: 'లక్షణాలు మాత్రమే',
    welcomeMessage: '👋 హలో! నేను మీ చర్మ ఆరోగ్య అసిస్టెంట్‌ని. విశ్లేషణ ప్రారంభించడానికి ప్రభావిత చర్మ ప్రాంతం చిత్రాన్ని అప్‌లోడ్ చేయండి.',
    uploadImage: 'చిత్రం అప్‌లోడ్ చేయండి',
    takePhoto: 'ఫోటో తీయండి',
    chooseFile: 'ఫైల్ ఎంచుకోండి',
    analyzing: 'మీ చిత్రాన్ని విశ్లేషిస్తోంది... దయచేసి వేచి ఉండండి.',
    imageReceived: '✅ చిత్రం అందింది! ఖచ్చితమైన రోగ నిర్ధారణ కోసం కొన్ని ప్రశ్నలకు సమాధానం ఇవ్వండి.',
    connectionError: '❌ కనెక్షన్ ఎర్రర్. సర్వర్ రన్ అవుతోందని నిర్ధారించుకుని మళ్ళీ ప్రయత్నించండి.',
    analysisError: '❌ క్షమించండి, చిత్రాన్ని విశ్లేషించడంలో లోపం. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    yes: 'అవును',
    no: 'కాదు',
    uploadTitle: 'చిత్రం అప్‌లోడ్ చేయండి',
    clickToUpload: 'అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    orDragDrop: 'లేదా డ్రాగ్ అండ్ డ్రాప్ చేయండి',
    fileTypes: 'PNG, JPG, JPEG (గరిష్టం 10MB)',
    analyzeImage: 'చిత్రాన్ని విశ్లేషించండి',
    analyzingBtn: 'విశ్లేషిస్తోంది...',
    tipsTitle: 'ఉత్తమ ఫలితాల కోసం చిట్కాలు',
    tip1: 'స్పష్టమైన, బాగా వెలుతురు ఉన్న ఫోటోలు ఉపయోగించండి',
    tip2: 'ప్రభావిత చర్మ ప్రాంతంపై దృష్టి పెట్టండి',
    tip3: 'అస్పష్టమైన లేదా దూరం నుండి తీసిన షాట్లను నివారించండి',
    tip4: 'చర్మ చిత్రాలను మాత్రమే చేర్చండి',
    conditionsTitle: 'మేము గుర్తించగల పరిస్థితులు',
    learnMore: 'మరింత తెలుసుకోండి',
    symptoms: 'సాధారణ లక్షణాలు',
    causes: 'కారణాలు',
    prevalence: 'వ్యాప్తి',
    severity: 'తీవ్రత',
    close: 'మూసివేయండి',
    acne: 'మొటిమలు',
    acneDesc: 'పింపుల్స్, బ్లాక్‌హెడ్స్, వైట్‌హెడ్స్',
    chickenpox: 'చికెన్‌పాక్స్',
    chickenpoxDesc: 'దురద బొబ్బలు, జ్వరం, దద్దుర్లు',
    healthySkin: 'ఆరోగ్యకరమైన చర్మం',
    healthySkinDesc: 'సాధారణ, ఆరోగ్యకరమైన రూపం',
    psoriasis: 'సోరియాసిస్',
    psoriasisDesc: 'ఎర్రటి మచ్చలు, వెండి పొలుసులు',
    skinCancer: 'చర్మ క్యాన్సర్',
    skinCancerDesc: 'మారుతున్న మచ్చలు, కొత్త పెరుగుదలలు',
    vitiligo: 'విటిలిగో',
    vitiligoDesc: 'తెల్ల మచ్చలు, రంగు కోల్పోవడం',
    cameraTitle: 'ఫోటో తీయండి',
    switchCamera: 'కెమెరా మార్చండి',
    capture: 'క్యాప్చర్',
    retake: 'మళ్ళీ తీయండి',
    usePhoto: 'ఫోటో ఉపయోగించండి',
    cameraError: 'కెమెరా యాక్సెస్ చేయడం సాధ్యం కాలేదు. అనుమతులు తనిఖీ చేయండి.',
    invalidFileType: 'చెల్లని ఫైల్ రకం. JPG, PNG లేదా WEBP చిత్రాలను అప్‌లోడ్ చేయండి.',
    fileTooLarge: 'ఫైల్ చాలా పెద్దది. గరిష్ట పరిమాణం 10MB.',
    imageTooSmall: 'చిత్రం చాలా చిన్నది. స్పష్టమైన, పెద్ద చిత్రాన్ని అప్‌లోడ్ చేయండి.',
    invalidImage: 'చిత్రాన్ని లోడ్ చేయడం సాధ్యం కాలేదు. మరొక ఫైల్ ప్రయత్నించండి.',
    clearImage: 'చిత్రం క్లియర్ చేయండి',
    clearAndTryAgain: 'క్లియర్ చేసి మళ్ళీ ప్రయత్నించండి',
    results: 'ఫలితాలు',
    confidence: 'నమ్మకం',
    recommendation: 'సిఫార్సు',
    disclaimer: 'నిరాకరణ: ఇది వైద్య రోగ నిర్ధారణ కాదు. ఆరోగ్య నిపుణుడిని సంప్రదించండి.',
    footerText: '© 2026 SkinAI డిటెక్టర్. విద్యా ప్రయోజనాల కోసం మాత్రమే.',
    privacyNote: 'మీ చిత్రాలు సురక్షితంగా ప్రాసెస్ చేయబడతాయి, నిల్వ చేయబడవు.',
  },
  kn: {
    // Kannada
    appName: 'SkinAI ಡಿಟೆಕ್ಟರ್',
    poweredBy: 'ಡೀಪ್ ಲರ್ನಿಂಗ್ ಮೂಲಕ ಚಾಲಿತ',
    home: 'ಮುಖಪುಟ',
    faq: 'ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    heroTitle: 'AI-ಚಾಲಿತ ಚರ್ಮ ರೋಗ ಪತ್ತೆ',
    heroSubtitle: 'ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ, ನಮ್ಮ AI ಸಹಾಯಕ ತ್ವರಿತ ರೋಗನిರ್ಣಯದಲ್ಲಿ ನಿಮಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ.',
    smartAssistant: 'ಸ್ಮಾರ್ಟ್ ಸಹಾಯಕ',
    imageOnly: 'ಚಿತ್ರ ಮಾತ್ರ',
    symptomsOnly: 'ರೋಗಲಕ್ಷಣಗಳು ಮಾತ್ರ',
    welcomeMessage: '👋 ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಚರ್ಮ ಆರೋಗ್ಯ ಸಹಾಯಕ. ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಲು ಪ್ರಭಾವಿತ ಚರ್ಮ ಪ್ರದೇಶದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    uploadImage: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    chooseFile: 'ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
    analyzing: 'ನಿಮ್ಮ ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ... ದಯವಿಟ್ಟು ಕಾಯಿರಿ.',
    imageReceived: '✅ ಚಿತ್ರ ಸ್ವೀಕರಿಸಲಾಗಿದೆ! ನಿಖರವಾದ ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಕೆಲವು ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.',
    connectionError: '❌ ಸಂಪರ್ಕ ದೋಷ. ಸರ್ವರ್ ಚಾಲನೆಯಲ್ಲಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಂಡು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    analysisError: '❌ ಕ್ಷಮಿಸಿ, ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸುವಲ್ಲಿ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    uploadTitle: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    clickToUpload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    orDragDrop: 'ಅಥವಾ ಎಳೆದು ಬಿಡಿ',
    fileTypes: 'PNG, JPG, JPEG (ಗರಿಷ್ಠ 10MB)',
    analyzeImage: 'ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    analyzingBtn: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    tipsTitle: 'ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗೆ ಸಲಹೆಗಳು',
    tip1: 'ಸ್ಪಷ್ಟವಾದ, ಚೆನ್ನಾಗಿ ಬೆಳಗಿದ ಫೋಟೋಗಳನ್ನು ಬಳಸಿ',
    tip2: 'ಪ್ರಭಾವಿತ ಚರ್ಮ ಪ್ರದೇಶದ ಮೇಲೆ ಗಮನ ಕೇಂದ್ರೀಕರಿಸಿ',
    tip3: 'ಮಸುಕಾದ ಅಥವಾ ದೂರದ ಶಾಟ್‌ಗಳನ್ನು ತಪ್ಪಿಸಿ',
    tip4: 'ಚರ್ಮದ ಚಿತ್ರಗಳನ್ನು ಮಾತ್ರ ಸೇರಿಸಿ',
    conditionsTitle: 'ನಾವು ಪತ್ತೆಹಚ್ಚಬಹುದಾದ ಸ್ಥಿತಿಗಳು',
    learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    symptoms: 'ಸಾಮಾನ್ಯ ರೋಗಲಕ್ಷಣಗಳು',
    causes: 'ಕಾರಣಗಳು',
    prevalence: 'ಹರಡುವಿಕೆ',
    severity: 'ತೀವ್ರತೆ',
    close: 'ಮುಚ್ಚಿ',
    acne: 'ಮೊಡವೆ',
    acneDesc: 'ಗುಳ್ಳೆಗಳು, ಕಪ್ಪು ಚುಕ್ಕೆಗಳು, ಬಿಳಿ ಚುಕ್ಕೆಗಳು',
    chickenpox: 'ಚಿಕನ್‌ಪಾಕ್ಸ್',
    chickenpoxDesc: 'ತುರಿಕೆ ಗುಳ್ಳೆಗಳು, ಜ್ವರ, ದದ್ದು',
    healthySkin: 'ಆರೋಗ್ಯಕರ ಚರ್ಮ',
    healthySkinDesc: 'ಸಾಮಾನ್ಯ, ಆರೋಗ್ಯಕರ ನೋಟ',
    psoriasis: 'ಸೋರಿಯಾಸಿಸ್',
    psoriasisDesc: 'ಕೆಂಪು ಮಚ್ಚೆಗಳು, ಬೆಳ್ಳಿ ಹುರುಪೆಗಳು',
    skinCancer: 'ಚರ್ಮದ ಕ್ಯಾನ್ಸರ್',
    skinCancerDesc: 'ಬದಲಾಗುತ್ತಿರುವ ಮಚ್ಚೆಗಳು, ಹೊಸ ಬೆಳವಣಿಗೆಗಳು',
    vitiligo: 'ವಿಟಿಲಿಗೋ',
    vitiligoDesc: 'ಬಿಳಿ ಮಚ್ಚೆಗಳು, ಬಣ್ಣ ಕಳೆದುಕೊಳ್ಳುವಿಕೆ',
    cameraTitle: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    switchCamera: 'ಕ್ಯಾಮೆರಾ ಬದಲಾಯಿಸಿ',
    capture: 'ಕ್ಯಾಪ್ಚರ್',
    retake: 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    usePhoto: 'ಫೋಟೋ ಬಳಸಿ',
    cameraError: 'ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ಅನುಮತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    invalidFileType: 'ಅಮಾನ್ಯ ಫೈಲ್ ಪ್ರಕಾರ. JPG, PNG ಅಥವಾ WEBP ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    fileTooLarge: 'ಫೈಲ್ ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ. ಗರಿಷ್ಠ ಗಾತ್ರ 10MB.',
    imageTooSmall: 'ಚಿತ್ರ ತುಂಬಾ ಚಿಕ್ಕದಾಗಿದೆ. ಸ್ಪಷ್ಟವಾದ, ದೊಡ್ಡ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    invalidImage: 'ಚಿತ್ರವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಬೇರೆ ಫೈಲ್ ಪ್ರಯತ್ನಿಸಿ.',
    clearImage: 'ಚಿತ್ರ ತೆರವುಗೊಳಿಸಿ',
    clearAndTryAgain: 'ತೆರವುಗೊಳಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    results: 'ಫಲಿತಾಂಶಗಳು',
    confidence: 'ವಿಶ್ವಾಸ',
    recommendation: 'ಶಿಫಾರಸು',
    disclaimer: 'ಹಕ್ಕುತ್ಯಾಗ: ಇದು ವೈದ್ಯಕೀಯ ರೋಗನಿರ್ಣಯವಲ್ಲ. ಆರೋಗ್ಯ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    footerText: '© 2026 SkinAI ಡಿಟೆಕ್ಟರ್. ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶಗಳಿಗೆ ಮಾತ್ರ.',
    privacyNote: 'ನಿಮ್ಮ ಚಿತ್ರಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಸ್ಕರಿಸಲಾಗುತ್ತದೆ, ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('preferredLanguage');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (key, params = {}) => {
    const template = translations[language]?.[key] || translations.en[key] || key;
    return Object.entries(params).reduce(
      (value, [paramKey, paramValue]) => value.split(`{${paramKey}}`).join(String(paramValue)),
      template
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;